code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/behavior.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/constraints.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/structure.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/typesystem.mps

Ported changes done on the maintenance branch

genutil: Exprresions in genUtil are available inside any mapping rule

---

code/diagram/languages/de.itemis.mps.editor.diagram.styles/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/behavior.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps

Note that
- This pull request has been tested with MPS 2018.2.3
- The merge with JetBrains/MPS-extensions master branch is already performed

Introduce DiagramButtonConfig & BoxButtonConfig in diagram editor

---

code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/generator/template/main@generator.mps
code/blutil/solutions/com.mbeddr.mpsutil.blutil.genutil.rt/models/genUtil.mps
code/blutil/tests/test.com.mbeddr.mpsutil.blutil.genutil/models/output.mps
code/blutil/tests/test.com.mbeddr.mpsutil.blutil.genutil/models/test@tests.mps
code/blutil/tests/test.com.mbeddr.mpsutil.blutil.genutil/test.com.mbeddr.mpsutil.blutil.genutil.msd
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

* use node reference instead of nodeID to identify if a template was already executed
* added generator test case

#140 executeOnce fails if template was copied

---

build.gradle

This PR enables the new feature of [Global Defaults](https://github.com/mbeddr/mps-gradle-plugin#providing-global-defaults) provided by the latest [mps-gradle-plugin](https://github.com/mbeddr/mps-gradle-plugin).

build: updated to latest mps-gradle-plugin

---

code/plaintextgen/languages/com.dslfoundry.plaintextgen.example.testlang/generator/template/main@generator.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/behavior.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/editor.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/intentions.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/plugin.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/structure.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/textGen.mps
code/plaintextgen/solutions/com.dslfoundry.plaintextgen.example.testlang.sandbox/models/plaintextgen_model.mps
gradlew.bat

Add literal tab support in PlainTextGen

---

code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime/plugin.mps

Keep a reference to the ClassLoaderManager to be able to unsubscribe
from it in onUnload().
Use the same module-reference to detect ourselves being unloaded.

grammarcells: avoid exceptions on dispose

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/de.itemis.mps.editor.dropdown.runtime.msd
code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/models/de/itemis/mps/editor/dropdown/runtime.mps

Just porting https://github.com/JetBrains/MPS-extensions/pull/230 from maintenance branch.

dropdown: fixed dropdown substitutions

---

code/multiline/languages/multiline/generator/template/main@generator.mps
code/richtext/languages/richtext/languageModels/editor.mps

This PR adds support for empty text in MultilineCells and also enables empty Words in richtext.

richtext: empty text support

---

code/widgets/languages/de.itemis.mps.editor.enumeration.demolang/models/editor.mps
code/widgets/languages/de.itemis.mps.editor.enumeration.demolang/models/structure.mps
code/widgets/languages/de.itemis.mps.editor.enumeration/generator/template/main@generator.mps
code/widgets/solutions/de.itemis.mps.editor.bool.sandbox/models/de/itemis/mps/editor/bool/sandbox.mps

- fixed CellModel_EnumCheckbox generator after 2019.2 migration
- corrected icon paths in the enumeration editor example

widgets: repaired EnumCheckbox editor

---

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps

smartReferent parameter available in substitution condition and description functions of the WrapperCell if wrapped concept has a smart reference. Allows now to filter substitute actions of WrapperCell based on the target referent of the wrapped smart concept node.

grammarcells: added smartReferent param in WrapperCell

---

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps

Cherry picked #309 onto master.

grammarcell: substitution post-process in wrapper cells (master)

---

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

this pull request addresses Issue #314

Fixing memory leaks in the Diagram DSL

---

code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps

I changed the collection types from lists to sets as it came up as a hotspot for large root nodes.

Improve performance for LayoutInterceptor#collectRequiredCells

---

code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/behavior.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/plugin.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/structure.mps
code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/textGen.mps
code/plaintextgen/solutions/com.dslfoundry.plaintextgen.example.plaintextflow/models/ExampleText.mps

Add an new option to the line ending setting of plaintextgen that will
generate files with the native line endings.
Signed-off-by: Bart vd. Meulen <bartvdrmeulen@gmail.com>

plaintextgen: Add option for native line endings #218

---

code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/boxmodel.mps
code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps

Layout of cells in richtext was broken after editing the text

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/solutions/com.fasterxml.jackson/com.fasterxml.jackson.msd

JDK was missing in Module where Jackson Stubs are.

Adds JDK as dependency to Jackson Stubs

---

code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/selection.mps
code/richtext/languages/richtext/richtext.mpl

Some selection actions failed because of a missing read access.
An exception was logged and nothing happened.

richtext selection behavior was broken

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/projectview/com.mbeddr.mpsutil.projectview.runtime/com.mbeddr.mpsutil.projectview.runtime.msd
code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime.mps
code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/plugin.mps
code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
code/projectview/com.mbeddr.mpsutil.projectview.vcs/models/com/mbeddr/mpsutil/projectview/vcs.mps
code/tables/languages/de.slisson.mps.tables/sandbox/models/de/slisson/mps/tables/sandbox.mps

Two issues are fixed here:
```
java.lang.NullPointerException
at com.mbeddr.mpsutil.projectview.runtime.tree.CustomProjectView.getId(CustomProjectView.java:124)
at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager$3.run(ProjectViewManager.java:142)
at jetbrains.mps.ide.ThreadUtils$LogExceptionsRunnable.run(ThreadUtils.java:81)
at jetbrains.mps.ide.ThreadUtils.runInUIThreadNoWait(ThreadUtils.java:58)
at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.activateView(ProjectViewManager.java:140)
at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.syncViews(ProjectViewManager.java:124)
at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.registerProject(ProjectViewManager.java:57)
at com.mbeddr.mpsutil.projectview.runtime.plugin.ProjectViewProjectPlugin_Project …
```

Fix NPE in CustomProjectView::getId

---

code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cells.mps
code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/vcs.mps

Fix for NoSuchMethodException in multiline.cells

---

code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

Diagram: fixed #478 - enable setting of height and width of ports

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/com.mbeddr.mpsutil.treenotation.runtime.msd
code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.sandbox/models/com/mbeddr/mpsutil/treenotation/sandbox.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/com.mbeddr.mpsutil.treenotation.sandboxlang.mpl
code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/models/editor.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/models/structure.mps
code/treenotation/com.mbeddr.mpsutil.treenotation/com.mbeddr.mpsutil.treenotation.mpl
code/treenotation/com.mbeddr.mpsutil.treenotation/generator/template/main@generator.mps
code/treenotation/com.mbeddr.mpsutil.treenotation/models/behavior.mps
code/treenotation/com.mbeddr.mpsutil.treenotation/models/editor.mps
code/treenotation/com.mbeddr.mpsutil.treenotation/models/structure.mps

This solves #481. See PR #482 for details. #482 was for MPS2020.3, this one is for master.

Implement generic insert handler for treenotation

---

code/.mps/modules.xml
code/.mps/product-workspace.xml
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
code/model-api/org.modelix.model.mpsadapters/org.modelix.model.mpsadapters.msd
code/model-api/org.modelix.model.repositoryconcepts/models/org.modelix.model.repositoryconcepts.structure.mps
code/model-api/test.org.modelix.model.mpsadapters/models/test.org.modelix.model.mpsadapters.wrappingmodelapi@tests.mps
code/model-api/test.org.modelix.model.mpsadapters/test.org.modelix.model.mpsadapters.msd

Based on the issue discussed in #485 I start with an initial proposal

Extending repository concepts

---

code/diagram/languages/de.itemis.mps.editor.diagram.demo.activity/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram.styles/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps

fixes #493 : enable the possibility to hide the context button show ports labels
- activity language example: added an example of DiagramButtonConfig

Diagram: fixed #493 - added a new style attribute "__show_ports_labels"

---

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/typesystem.mps

This is the PR #498 for maintenance/mps2021.1.

Replace "Will be inlined. Override will not work." warning by info.

---

code/math/solutions/de.itemis.mps.editor.math.runtime/models/de/itemis/mps/editor/math/runtime.mps

Fixes #458.  The `Graphics2D.drawString` implementation for ligatures doesn't like drawing strings when the scaling is 0.

Add null check to drawString method in math language

---

code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
code/model-api/org.modelix.model.repositoryconcepts/models/org.modelix.model.repositoryconcepts.structure.mps
code/model-api/test.org.modelix.model.mpsadapters/models/test.org.modelix.model.mpsadapters.dummyusedintests@tests.mps
code/model-api/test.org.modelix.model.mpsadapters/models/test.org.modelix.model.mpsadapters.wrappingmodelapi@tests.mps
code/model-api/test.org.modelix.model.mpsadapters/test.org.modelix.model.mpsadapters.msd

Correcting errors and completing the information available on dependencies of modules and models. We also consider devkits and the scope of dependencies.
Some tests added.

Completing & correcting MPS adapters

---

code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cells.mps
code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/runtime/plugin.mps

It can be disabled in preferences > other settings > multiline or through class MultilineSettingsPage.

Multiline: Add spellchecking (enabled by default)

---

.travis.yml

Travis CI is not used anymore.

Build: remove travis.yml

---

build.gradle
code/.mps/modules.xml

This PR adds a check to the build script for the paths in the modules.xml and adds a precheck task for registering other checks that are run before every other task.
Do we need any other pre-checks at the moment?

[Breaking] Build script: check paths in modules.xml

---

README.md
build.gradle
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps
code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
code/widgets/languages/de.itemis.mps.editor.collapsible/de.itemis.mps.editor.collapsible.mpl
code/widgets/languages/de.itemis.mps.editor.enumeration/runtime/models/de.itemis.mps.editor.enumeration.runtime.mps
docs/index.md

[Release notes](https://youtrack.jetbrains.com/issues/MPS?q=%23Resolved%20Fix%20versions:%202021.3.2&_ga=2.175169122.1193796523.1669010815-2058359210.1628057624&_gl=1*1ig05uz*_ga*MjA1ODM1OTIxMC4xNjI4MDU3NjI0*_ga_9J976DJZ68*MTY2OTEyMTE2Ny40MjkuMS4xNjY5MTIyMTQ0LjYwLjAuMA..)

Migrate to 2021.3.2

---

code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

This PR adds  new query condition that can be used to manipulate whether auto layouting happens or not. It also deprecates the boolean flag runAutoLayoutOnInit in favour of new query function. The flag is still supported but precedence is given to the new function.

Add query condition for auto-layouting of diagrams

---

build.gradle

This change was lost in a merge.

Updated mps-gradle-plugin back to version 1.13

---

code/.mps/modules.xml
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.sandbox/models/de/itemis/mps/editor/diagram/sandbox.mps
code/htmlcell/languages/de.itemis.mps.editor.htmlcell.demolang/models/de.itemis.mps.editor.htmlcell.demolang.editor.mps
code/third-party/solutions/MPS.ThirdParty/MPS.ThirdParty.msd

The path changed to app.jar and it was missing in modules.xml

Fix MPS.ThirdParty module

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/third-party/solutions/MPS.ThirdParty/MPS.ThirdParty.msd

Let's try fixing this stub again. I've tested it by installing the plugin in MPS. It seems to work.

MPS.ThirdParty: don't copy app.jar to avoid class loading conflicts

---

code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps

Add back intentions icon

---

code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps

This attempts to fix issue #634 . I could not reproduce it after cherry-picking the changes from the master branch commit  2c5c529cb59472ad20e34854a167ffb877d404ad into the branch maintenance/mps20222.

Attempt to fix issue #634

---

build.gradle
settings.gradle

remove old nexus repository,
update usage of de.itemis.mps.gradle plugin according to https://github.com/mbeddr/mps-gradle-plugin/tree/v1.x#configuring-the-plugin-repository

Remove old nexus repository and update configuration

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/languages/de.itemis.model.merge.diamond/models/de.itemis.model.merge.diamond.structure.mps
code/languages/de.itemis.model.merge/de.itemis.model.merge.mpl
code/languages/de.itemis.model.merge/models/de.itemis.model.merge.structure.mps
code/languages/de.itemis.model.simple.demo.collection.keeper/de.itemis.model.simple.demo.collection.keeper.mpl
code/languages/de.itemis.model.simple.demo.collection.keeper/models/de.itemis.model.simple.demo.collection.keeper.structure.mps
code/languages/de.itemis.model.simple.demo.collection/de.itemis.model.simple.demo.collection.mpl
code/languages/de.itemis.model.simple.demo.collection/models/de.itemis.model.simple.demo.collection.structure.mps
code/languages/de.itemis.model.simple.demo.reference/de.itemis.model.simple.demo.reference.mpl
code/languages/de.itemis.model.simple.demo.reference/models/de.itemis.model.simple.demo.reference.structure.mps
code/mouseselection/solutions/de.itemis.mps.selection.runtime/models/de/itemis/mps/selection/runtime/plugin.mps
code/shadowmodels/solutions/de.q60.mps.shadowmodels.runtime/de.q60.mps.shadowmodels.runtime.msd
code/shadowmodels/solutions/de.q60.mps.shadowmodels.runtime/models/engine.mps
code/solutions/de.itemis.model.merge.simple.demo/models/de.itemis.model.merge.simple.demo.plugin.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps
code/treenotation/com.mbeddr.mpsutil.treenotation/generator/template/main@generator.mps

Executed rerunnable migrations, after `git clean -xdf` and `./gradlew run_tests` and `make project`

Executed rerunnable migrations

---

code/linenumbers/de.itemis.mps.linenumbers/models/de.itemis.mps.linenumbers.plugin.mps

Issue:  #672
Line numbers in "MPS model viewer" are shown as in "Side-by side viewer"

Fixed alignment of line numbers when shown on right editor side

---

CHANGELOG.md
code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/695

Querylist: support style attributes in in the default editor cell

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/com.mbeddr.mpsutil.grammarcells.tests.msd
code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/models/com/mbeddr/mpsutil/grammarcells/tests@tests.mps

The generator of the MPS editor language generates an additional collection cell around cells inside an alternation cell that also have a rendering condition. The problem with that is, that it has a horizontal layout which breaks surrounding indent layouts.

fix(celllayout): additional horizontal cell was generated around optional cells

---

CHANGELOG.md
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps
code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.structure.mps
code/pagination/languages/de.itemis.mps.editor.pagination/generator/templates/de.itemis.mps.editor.pagination.generator.templates@generator.mps
code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/de.itemis.mps.editor.pagination.runtime.msd
code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.pages.mps
code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.ui.mps

The current page text is now editable.

Pagination: Support entering page numbers directly

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/tables/languages/de.slisson.mps.tables.demolang/languageModels/editor.mps
code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps
code/tables/languages/de.slisson.mps.tables/languageModels/editor.mps
code/tables/languages/de.slisson.mps.tables/languageModels/structure.mps
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertColumnLeft.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertColumnLeft_dark.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertColumnRight.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertColumnRight_dark.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertRowAbove.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertRowAbove_dark.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertRowBelow.svg
code/tables/languages/de.slisson.mps.tables/runtime/icons/insertRowBelow_dark.svg
code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/plugin.mps

As the title already tells, I've added some additions to https://github.com/JetBrains/MPS-extensions/pull/700.

tables: implement column table actions and update icons

---

CHANGELOG.md
code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps
code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/behavior.mps
code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps

mpsutil.intentions: don't make intentions available in read-only cells when the annotation showIntentionInReadyOnlyCell is not added

Change read-only intentions default behavior

---

build.gradle
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

* Remove Maven local repository.
* Remove Gradle wrapper configuration.
* Disable incremental build, it doesn't work well.
* Fail Gradle build if tests fail.
* Other minor improvements.

Build improvements

---

code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime.mps
code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps

This PR fixes https://github.com/JetBrains/MPS-extensions/issues/707 and https://github.com/JetBrains/MPS-extensions/issues/628.

projectview: register custom project in the AbstractProjectViewPane extension point

---

CHANGELOG.md
README.md
code/.mps/modules.xml
code/blutil/languages/com.mbeddr.mpsutil.blutil/blutil.mpl
code/blutil/languages/com.mbeddr.mpsutil.blutil/generator/template/main@generator.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/behavior.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/constraints.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/dataFlow.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/editor.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/structure.mps
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/typesystem.mps
code/blutil/solutions/com.mbeddr.mpsutil.blutil.genutil.rt/models/genUtil.mps
code/blutil/tests/test.com.mbeddr.mpsutil.blutil/models/test.com.mbeddr.mpsutil.blutil.ifInstanceOf@tests.mps
code/blutil/tests/test.com.mbeddr.mpsutil.blutil/test.com.mbeddr.mpsutil.blutil.msd
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
docs/extensions/bl-extensions/blutil.md

Example:
```
test withElseIfAndElse { 
node<ClassConcept> node = new node<ClassConcept>(); 
int result; 
ifInstanceOf (node is ClassConcept cls) { 
result = cls.isNotNull ? 0 : 1; 
} else ifInstanceOf (node is AbstractCatchClause acc) { 
result = acc.isNotNull ? 2 : 3; 
} else ifInstanceOf (node is AbstractClassifierReference acr) { 
result = acr.isNotNull ? 5 : 6; 
} else { 
result = 7; 
} 
assert 0 equals result ; 
}
```

com.mbeddr.mpsutil.blutil: Add a new ifInstanceOf statement that supports else if and else branches

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/multiline/languages/demolang/demolang.mpl
code/multiline/languages/demolang/languageModels/editor.mps
code/multiline/languages/demolang/languageModels/structure.mps
code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cells.mps
code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/runtime.msd
code/multiline/solutions/de.slisson.mps.editor.multiline.sandbox/models/de/slisson/mps/editor/multiline/sandbox/sandbox.mps

The PR fixes an issue when pressing shift+enter didn't enter a new line in the current text but in the next collection in the editor. Partly fixes https://github.com/JetBrains/MPS-extensions/issues/769.

Multiline: Add a dummy role 

---

build.gradle
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

fix remaining problems of #790

build:Third.Party: added module to default layout

---

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/constraints.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/802

grammarcells: Remove duplicate editor cell models from the cc menu

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
code/hacks/languages/de.slisson.mps.reflection/de.slisson.mps.reflection.mpl
code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/com.mbeddr.mpsutil.editor.querylist.demolang.mpl
code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/com.mbeddr.mpsutil.editor.querylist.runtime.msd
code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com.mbeddr.mpsutil.editor.querylist.runtime.plugin.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com/mbeddr/mpsutil/editor/querylist/runtime.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist.sandbox/models/com/mbeddr/mpsutil/editor/querylist/sandbox.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/editor.mps
code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/structure.mps
docs/extensions/editor/querylist.md

Open question: 
- Could[ QueryListChecker#needsUpdate](http://127.0.0.1:63320/node?ref=r%3A5f74240b-ce7f-4ae5-99bc-bf1a210bda6d%28com.mbeddr.mpsutil.editor.querylist.runtime.plugin%29%2F4268492325946535452) be implemented and if so, how?
- Is enabling the model checker possible for nodes without a model? (my guess: no)
The feature can be tested [here](http://127.0.0.1:63320/node?ref=c58b797b-c53c-4442-abff-4d54c72169ea%2Fr%3A5f236bd8-eb21-40b6-825a-9e614ca27175%28com.mbeddr.mpsutil.editor.querylist.sandbox%2Fcom.mbeddr.mpsutil.editor.querylist.sandbox%29%2F3813940761427382564).

Querylist: support model checking

---

CHANGELOG.md
code/richtext/languages/richtext/languageModels/editor.mps
code/richtext/languages/richtext/languageModels/plugin.mps

The action is overwritten in the richtext language but was somehow lost in a merge from maintenance/mps20213 to maintenance/mps20222.

Add back duplicate action

---

CHANGELOG.md
code/projectview/com.mbeddr.mpsutil.projectview/generator/template/main@generator.mps
code/projectview/com.mbeddr.mpsutil.projectview/languageModels/behavior.mps
code/projectview/com.mbeddr.mpsutil.projectview/languageModels/constraints.mps

The variable `mpsProject` should be used instead.

com.mbeddr.mpsutil.projectview: remove the broken parameter project from the is default condition

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/layout.mps
code/diagram/languages/de.itemis.mps.editor.diagram.demo.elk/de.itemis.mps.editor.diagram.demo.elk.mpl
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/de.itemis.mps.editor.diagram.runtime.msd
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

comp.diagram: remove dependency to de.q60.mps.collections.libs

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/celllayout/languages/de.itemis.mps.celllayout/models/styles/editor.mps
code/celllayout/languages/de.itemis.mps.editor.celllayout.sandboxlang/de.itemis.mps.editor.celllayout.sandboxlang.mpl
code/celllayout/languages/de.itemis.mps.editor.celllayout.sandboxlang/models/editor.mps
code/celllayout/languages/de.itemis.mps.editor.celllayout/de.itemis.mps.editor.celllayout.mpl
code/celllayout/languages/de.itemis.mps.editor.celllayout/models/behavior.mps
code/celllayout/languages/de.itemis.mps.editor.celllayout/models/de.itemis.mps.editor.celllayout.constraints.mps
code/celllayout/languages/de.itemis.mps.editor.celllayout/models/structure.mps
code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/layout.mps
code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

More details: https://github.com/JetBrains/MPS-extensions/pull/610

Celllayout: add the option to have the root cell occupy the full editor width

---

build.gradle
code/diagram/languages/de.itemis.mps.editor.diagram.demo.elk/models/de.itemis.mps.editor.diagram.demo.elk.structure.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/behavior.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.demo.elk.sandbox/models/de.itemis.mps.editor.diagram.demo.elk.sandbox.mps
code/shadowmodels/languages/de.q60.mps.virtualinterfaces/models/plugin.mps
code/shadowmodels/solutions/de.q60.mps.polymorphicfunctions.runtime/models/plugin.mps
code/solutions/de.itemis.model.merge.runtime/de.itemis.model.merge.runtime.msd

* Use `Remigrate` task from mps-gradle-plugin.
* Exclude diagram language migration 0 because it is currently not rerunnable.
* Execute all pending migrations.
* Execute rerunnable migrations.

Prepare to run migrations as part of the build

---

CHANGELOG.md
code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

Fixing several bugs in Project view

---

code/blutil/languages/com.mbeddr.mpsutil.blutil/generator/template/main@generator.mps

COPY-SRC for StatementList tries to insert StatementList inside a body of a method, where Statements are expected.

blutil: PerformanceProfiler - Statement vs StatementList

---

code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/de.itemis.mps.editor.diagram.migration.mps
code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps

Backporting bugfix
(cherry picked from commit 81a2d7acce468dfb2af40c3e3e191cf6ecffdf38)

mps.tables: make the dummy link work in the cell inspector

---

CHANGELOG.md
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

*IDragPaletteEntry* and *IPaletteEntry* are not mutually exclusive anymore and can be implement by one class.

editor.diagram: merge GenericTransferable and mxGraphTransferable

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/de.itemis.mps.editor.diagram.runtime.msd
code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
code/model-api/org.modelix.model.mpsadapters/org.modelix.model.mpsadapters.msd
code/shadowmodels/solutions/de.q60.mps.shadowmodels.debugview/de.q60.mps.shadowmodels.debugview.msd
code/shadowmodels/solutions/de.q60.mps.shadowmodels.debugview/models/pf.mps

rerouted all dependencies on com.google.common.collect(MPS.IDEA/) to com.google.common.collect(de.q60.mps.collections.libs/)

rerouted all dependencies on guava collections from MPS.IDEA to de.q60.mps.collections.libs

---

build.gradle

The publish task fails for some reason.

Revert "build(deps): bump com.jetbrains.mps:mps-prerelease from 243.21565.111 to 243.21565.130"

---

code/mouseselection/languages/de.itemis.mps.selection.intentions/languageModels/typesystem.mps

Manually created PR because the automation didn't work (the branch was pushed by github-actions bot and pushes by this bot don't trigger further actions).

Merge 2022.2 → 2022.3

---

code/widgets/solutions/de.itemis.mps.editor.bool.runtime/models/de/itemis/mps/editor/bool/runtime.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/1040

editor.bool: use true/false as default substitute text if they are not specified

---

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/icons/erDiagram.svg
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/icons/erDiagram_dark.svg
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps
code/langvis/solutions/com.dslfoundry.langvis.plugin/models/com.dslfoundry.langvis.plugin.plugin.mps

We need icons for all tools, since the new UI doesn't show tool labels.

Add icons to the langvis and diagram tool

---

code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/models/de/itemis/mps/editor/dropdown/runtime.mps

The dropdowns now look more similar to JCheckBoxes with the IntelliJ theme.

editor.dropdown: improve border color and arrow drawing

---

code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/selection.mps
code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps
code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps

Respective methods have been deprecated since 2024.1 and removed in 2025.1

No need for model when accessing clipboard data

---

CHANGELOG.md
code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

Some more options of the diagram component like the pan amount and minimum scaling can now be customized in the diagram editor.

editor.diagram: make some graph component options customizable

---

code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/models/test/de/itemis/mps/editor/diagram/solution@tests.mps

Now all tests should be running in the CI.

editor.diagram: improve some tests

---

code/blutil/languages/com.mbeddr.mpsutil.blutil/blutil.mpl
code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/editor.mps
code/blutil/solutions/com.mbeddr.mpsutil.blutil.genutil.rt/models/genUtil.mps
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

mpsutil.blutil:add a completion style for models that have a visibility=internal

---

code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/1003

editor.diagram: add null checks for DiagramCreationContext.getRootGraph

---

code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.plugin.utils.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/977

editor.pagination: don't allow opening of nodes that are not part of a model

---

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/typesystem.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/606

Grammarcells: add a warning when the internal grammarCellls cell is used

---

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/348

editor.diagram: improve the accessor assignment method

---

CHANGELOG.md
code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cells.mps
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/838

editor.multiline: fix a StringIndexOutOfBoundsException when trying to delete the last character of the multiline cell

---

CHANGELOG.md
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.sandbox/models/com/mbeddr/mpsutil/treenotation/sandbox.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/models/editor.mps

- fixes https://github.com/mbeddr/mbeddr.core/issues/1502

mpsutil.treenotation: make the delete button also work for leaf cells

---

docs/extensions/utils/model-merger.md

Some extra setup is needed to make the merge language work in your solution.
Thanks to @alexanderpann and @eugenschindler for explaining how to make things work.

Add documentation on how to set up solution/model with merge language

---

CHANGELOG.md
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/compare/languages/de.itemis.mps.compare/compare.mpl
code/compare/languages/de.itemis.mps.compare/generator/template/de.itemis.mps.compare.generator.template.main@generator.mps
code/compare/languages/de.itemis.mps.compare/languageModels/de.itemis.mps.compare.dataFlow.mps
code/compare/languages/de.itemis.mps.compare/languageModels/de.itemis.mps.compare.editor.mps
code/compare/languages/de.itemis.mps.compare/languageModels/de.itemis.mps.compare.structure.mps
code/compare/languages/de.itemis.mps.compare/languageModels/de.itemis.mps.compare.typesystem.mps
code/compare/solutions/de.itemis.mps.compare.pattern.test/models/de.itemis.mps.compare.pattern.test.basic@tests.mps
code/compare/solutions/test.de.itemis.mps.compare/models/test.de.itemis.mps.compare.ts@tests.mps
code/compare/solutions/test.de.itemis.mps.compare/test.de.itemis.mps.compare.msd
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

Example:
```java
test testEqualValuesWithinDelta { 
float expected = 3.0f; 
float actual = 3.001f; 
float delta = 0.01f; 
assert expected equals actual with tolerance delta ; 
}
test testValuesOutsideDelta { 
float expected = 3.0f; 
float actual = 3.05f; 
float delta = 0.01f; 
assert expected not equals actual with tolerance delta ; 
}
```

itemis.mps.compare: create a new concept to compare floating point numbers in tests

---

CHANGELOG.md
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps

The folding buttons are still enabled.
- fixes https://github.com/mbeddr/mbeddr.core/issues/2046

mpsutil.treenotation: Tree cells now don't show insert/delete buttons when they are read-only.

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
code/diagram/languages/de.itemis.mps.editor.diagram/de.itemis.mps.editor.diagram.mpl
code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps

(cherry picked from commit 6c5a6e1e1c188d5606e40c0aee325eb1c7e353c1)

Backport: editor.diagram: fix the style generation for edges

---

code/blutil/languages/com.mbeddr.mpsutil.blutil/blutil.mpl
code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

- fixes https://github.com/JetBrains/MPS-extensions/issues/1301

Add a missing dependency in de.itemis.mps.blutil 

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

With MPS-38286 fix, generator of build language checks plugin dependencies with respect to used languages and their runtimes, and reports errors if plugin dependencies are insufficient. The fix adds dependencies into plugin descriptors from build project.

MPS-38286 fix reported incomplete plugin dependencies

---

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps

Fix the build of MPS-extensions with the upcoming 2024.1.4: https://teamcity.jetbrains.com/buildConfiguration/MPS_20241_Distribution_Extensions/5191827?buildTab=log&focusLine=188&linesState=126.188.239&logView=flowAware

intentions, compare: add newly necessary plugin dependencies

---

.github/renovate.json5

Also enable automerge for MPS updates on Wednesday mornings.

Enable Renovate on maintenance branches

---

.github/renovate.json5

Renovate updates

---

CHANGELOG.md
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

Added changes to the changelog model previously added directly to the CHANGELOG.md

updated changelog model

---

CHANGELOG.md
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
code/tables/languages/de.slisson.mps.tables/languageModels/behavior.mps

fix(tables): added Object to joinType in TableCellQueryGetCell

---

CHANGELOG.md
code/compare/languages/com.mbeddr.mpsutil.compare/generator/template/main@generator.mps
code/compare/solutions/com.mbeddr.mpsutil.comparator.diff.tests/models/com.mbeddr.demo.comparator.diff.tests.diffs@tests.mps
code/compare/solutions/com.mbeddr.mpsutil.comparator/models/DiffView.mpsr
code/compare/solutions/com.mbeddr.mpsutil.comparator/models/MPSNodeComparator.mpsr
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps

Improvements to comparator and compare language

---

CHANGELOG.md
code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
code/spellcheck/solutions/de.itemis.mps.spellcheck.runtime/models/de.itemis.mps.spellcheck.runtime.plugin.mps

Otherwise, there can be a `ProgressCanceledException` happening when the menu is opened.

mps.spellcheck: Update words to dictionary intention in background
