code/mps-blutil/languages/com.mbeddr.mpsutil.blutil.genutil/com.mbeddr.mpsutil.blutil.genutil.mpl, code/mps-blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/constraints.mps, code/mps-build/solutions/de.slisson.mps.all.build/models/de/slisson/mps/all/build.mps
The constrains for the newly introduced baselanguage expressions were missing. The new expressions:
`RootMappingExecuteOnceExpression`
`RootMappingHasBeenExecutedExpression`
`SetRootMappingHasBeenExecutedExpression`
should only be usable in `Root_MappingRule`s but in no toher context.
This pullrequest would introduce the missing contraints.
=> mbeddr.mpsutil.blutil.genutil: added can be child constraints

docs/extensions/diagrams.md
While reading the [documentation of the diagram language](https://jetbrains.github.io/MPS-extensions/extensions/diagrams/) I noticed that the namespace in the documentation doesn't match the namespace of the code. This pull request adjusts the namespace in the documentation.
=> fix language namespace of diagram editor (documentation)

code/richtext/languages/richtext/languageModels/behavior.mps
Normalise the text that is created in RichtextUtil. Otherwise the text
would need to be normalised directly after it has been inserted into the
model. Often causing the carret to be positioned in a strange way.
=> richtext: normalise text after creation

code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/models/de/itemis/mps/editor/dropdown/runtime.mps, code/widgets/solutions/de.itemis.mps.editor.dropdown.sandbox/de.itemis.mps.editor.dropdown.sandbox.msd, code/widgets/solutions/de.itemis.mps.editor.dropdown.sandbox/models/de/itemis/mps/editor/dropdown/sandbox.mps
Currently, if the collection is empty when you click the drop-down button, the completion menu will also be empty. When using the keyboard the completion menu is correctly populated. 
When using the keyboard the editor label cell is used as input to the substitute chooser, while the combo box always uses the editor cell collection. To fix this I always pass into the substitute chooser the last leaf. I am sure if this is a good solution but it seems to work for this particular scenario.
To play around one can just use the existing example in the sandbox:
http://127.0.0.1:63320/node?ref=r%3A33040f6a-f60b-472b-aae3-ed4400e941e2%28de.itemis.mps.editor.dropdown.sandbox%29%2F4141535073103138147&project=mps-extensions
=> dropdowncell: always feed node substitutor with last leaf

code/conditional-editor/languages/de.slisson.mps.conditionalEditor/generator/template/main@generator.mps
The `reduce_CellModel_PriorityInfo` template now makes use of the `SetBigCellProperty` template switch. This makes sure that whenever appropriate, the `setCellContext` method will also be called beyond setting the `big` flag.
=> PriorityInfoCell reduction rule generates proper setup block for the editor cell

build.gradle, code/languages/de.itemis.mps.modelmerger/sandbox/de.itemis.mps.modelmerger.testhelper.msd
- updates to the latest MPS 2018.2.5
- refactored computation of the mpsVersion to handle different mps release types
=> updated mps version to 2018.2.5 / refactored mpsVersion config

code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/generator/template/main@generator.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/constraints.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/editor.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/structure.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil.genutil/models/typesystem.mps, code/blutil/solutions/com.mbeddr.mpsutil.blutil.genutil.rt/models/genUtil.mps, code/blutil/tests/test.com.mbeddr.mpsutil.blutil.genutil.lang/generator/template/main@generator.mps
In many generators we don't want to generate when we are in node or
editor tests. For that we typically check if there is any concept from
the jetbrains.mps.lang.test langauge in the original model. In order
to have this logic in a common place there is now a expression that
checks for it.
=> blutil: add expression to detect test models

code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
Given a table editor that contains a collection inside its rows (in my case, a switch statement displayed as a decision table, so each switch case is a row and the second column is the switch case body, which contains a statement list), moving a child of a table cell up- or downwards with Ctrl+Shift+Up/Down is non-deterministic: The child randomly ends up either in one of the other rows above or below, or above/below the table.
Apparently, this is caused by the ChildsTracker utility class using HashSets to remember the table's child EditorCells. I didn't try to fully grasp the implementation, but in any case, replacing the HashSets with LinkedHashSets seems to help.
=> Tables: Make moving children between rows deterministic

code/shadowmodels/languages/de.q60.mps.shadowmodels.transformation/models/intentions.mps
When doing any in-place transformation with the shadow modells ( input element is of same type as output) the manual mapping of properties is quite cumbersome. 
To automate this an intention is implemented. 
In the case where the output node concept matches the concept of any `TransformationParameter`  the properties of this concept are mapped automatically for the output element.
=> shadowmodels.transfor.intentions: added intention to map all properties

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps
The caption of the actions `RotateBoxClockwiseAction`, `FlipBoxAction` and `RotateBoxCounterClockWiseAction` were all "Rotate Diagram Box". I changed this to:
* `RotateBoxClockwiseAction`: "Rotate Diagram Box Clockwise"
* `FlipBoxAction`: "Flip Diagram Box Horizontally"
* `RotateBoxCounterClockWiseAction`: "Rotate Diagram Box Counterclockwise"
=> Fix captions of rotate and flip diagram component

code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/gridmodel.mps
After profiling a client using tabular editors brought me to this small improvement. 
My fix checks directly if the row-headers are empty or not without firstly calling clone() on them.
=> tables: removed unnecessary clone() when checking only if the row-headers are empty or not

.gitignore, build.gradle, mkdocs.yml, requirements.txt
move the logic to generate the documentation into gradle. This allows
us to update and maintain the documentation without depending on the
build server infrastructure.
=> build: install pip and run mkdocs from gradle

code/widgets/languages/de.itemis.mps.editor.collapsible/generator/template/main@generator.mps
Several $IF$ macros in the template had a StatementList for "then"
branch but a ReturnStatement for "else". All branches of those $IF$s are
now StatementLists.
=> Fix generator warnings when using collapsible cells

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
Removed the idea version block from the plugin xml of plaintext gen.
None of the plugins in the mps extensions use this feature anymore.
fixed #222
=> plaintext.gen: remove idea version from plugin.xml

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/de.itemis.mps.editor.dropdown.runtime.msd, code/widgets/solutions/de.itemis.mps.editor.dropdown.runtime/models/de/itemis/mps/editor/dropdown/runtime.mps
The previous implementation used to set the active substitution on the last leaf, which in practice
meant that generally it was activated for the most right cell.
In this implementation we want to use the outmost editor cell from the dropdown to active the
substitution. The case we have to care for, is when in example we have no value set yet.
In that case, we have to look inside the EdiotrCell_Collection and activate the substitution for the
inner cell.
=> dropdown: fixed dropdown substitutions

code/richtext/languages/richtext/languageModels/editor.mps
* Search for the cell to delete starting from the current cell, not its
parent. This prevents deletion of the owner of the Text/TextBlock while
trying to delete a word.
* Normalize the text blocks explicitly after deleting a (word) cell, to
be able to save/restore selection properly.
=> Fix weird behavior of word deletion in rich text

code/diagram/languages/de.itemis.mps.editor.diagram.demolang/languageModels/editor.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.sandbox/models/de.itemis.mps.editor.diagram.sandbox_lib.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.sandbox/models/de/itemis/mps/editor/diagram/sandbox.mps
This commit implements the extension, and showcases it in the diagram.demolang language and its sandbox.
=> diagram: fixing #257 - in the diagram palette, a folder can contain sub-folders

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
When you use an editor with a `SplittableCell` in a generator template (e.g. StringLiteral, NumberLiteral), the usual "Add Property Macro" intention is not available for the property behind the `SplittableCell`. This happens because `SplittableCell` doesn't have propery cell context with property infomation that is checked from the intention precondition (see method j.m.l.generator.helper.EditingUtil#isPropertyMacroApplicable).
In order to fix this I have added custom cell factory method generation template for the SplittableCell that sets cell context exactly how it's done for CellModel_Property. Just using factory method generation template for the CellModel_Property directly is not possible because then `SplittableCell` doesn't work as intended (splitting doesn't work).
=> grammarcells: provide cell context in SplittableCell factory method

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
This was requested by JetBrains (@mvlassiev) for the upcoming 2019.3 release, for the new functionality of automatic upload of MPS Extensions to the JetBrains plugin repository. The rationale is that the <description> fields are necessary to properly search for relevant plugins.
@coolya if you could have a look and merge this, that would be very appreciated!
=> Add descriptions and vendors to extensions that didn't yet have any

.idea/gradle.xml, .idea/modules.xml, build.gradle
Required git command is executed as a first build step on the build server.
=> build: removed noneffective commandLine (only one per Exec possible)

docs/index.md
Now that we migrated to 2019.3 we should keep the docu in sync. This PR just
updates the table with the maintained MPS versions.
=> updated table of currently maintained MPS versions

docs/building.md
Now that we are using MPS 2019.3 the preconditions for building MPS-extensions from sources 
have chaged. Users have to have JDK 11 installed. 
In addtion the link to the current MPS verions in the build.gradle file was updated.
=> updated documentation how to build from sources

code/tooltips/solutions/de.itemis.mps.tooltips.runtime/models/de/itemis/mps/tooltips/runtime.mps
in case the toolip is used in the editor that renders children or descender nodes
of the same of concept and using the same editor, wrong tooltip was shown for the original
node corresponding to the tooltip of the last node rendered in the original editor. This
was due to the overwritten tooltip registration per tooltip id by rendered descender nodes.
Now only the first tooltip is registered per context preventing this unintended overwrite.
=> fixed wrong tooltip display issue

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps
- Adds support for substitution post-process function in WrapperCell for all kinds of supported wrapped cells. 
- Post-process function now also gets the parent node passed as a parameter.
=> grammarcell: substitution post-process in wrapper cells

code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/intentions.mps
The intentions for selections of multiple nodes did not have an
isApplicable set. So they appear alwasys when multiple nodes are
selected.
Add a isApplicable to check if the selection contains plaintextgen
concepts.
fixes #301
Signed-off-by: Bart vd. Meulen <bartvdrmeulen@gmail.com>
=> plaintextgen: Fix intentions appearing for none plaintextgen concepts

code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps
Toggling a collapsible changes the cell tree outisde of the editor
update cycle. The caching introduced to improve the performance
(see #320) doesn't work in that case.
=> backport: Borders were not painted for tables inside a collapsible cell

code/plaintextgen/languages/com.dslfoundry.plaintextflow/models/behavior.mps
As reported by @KemalSoysal and @eugenschindler: the new versions of MPS check for concepts that do not implement abstract methods. Such errors are currently reported on the plaintextflow language.
This commit should fix this by implementing the following methods in various concepts:
* Width
* Editor_View_Width
* TextGen (this method only throws an Exception, since the concepts in this language are meant to be reduced and not used by TextGen)
=> Implement abstract methods in plaintextflow concepts

README.md
Fix 382 in README.md: Java 11 is needed instead of Java 8.
Signed-off-by: Cornel Izbasa <badc0ded@gmail.com>
=> README.md: fix issue 382 - specify Java 11 is needed (instead of Java 8)

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps
After the migration to the new constraints API canBeAncestor constraints
were only checked for the parent and not for all ancestors. The old
API iterated over all ancestors. The new API requires the caller to
iterate over all ancestors.
Fixes #381
=> grammar cells: can be ancestor constraints weren't applied correctly

code/langvis/languages/com.dslfoundry.langvis.demolang/models/structure.mps, code/langvis/solutions/com.dslfoundry.langvis.plugin/models/com.dslfoundry.langvis.plugin.plugin.mps
This fixes the property doubling occurring for classes rendered in the diagrams created by `langvis/solutions/com.dslfoundry.langvis.plugin`.
The fix eliminates a surplus `for` loop.
The fix also adds a property to the classes `A` and `B` of `langvis/languages/com.dslfoundry.langvis.demolang` to be able to see potential regressions.
The diagrams seem to be correctly rendered now:
Thanks for your feedback and consideration!
=> langvis: fix #386 - property doubling in uml diagram

code/langvis/languages/com.dslfoundry.langvis.demolang/models/structure.mps, code/langvis/solutions/com.dslfoundry.langvis.plugin/models/com.dslfoundry.langvis.plugin.plugin.mps
Indicate root node with custom spot: #394 
Turn on "Hierarchy" option by default, and render extended base concept when "Hierarchy" is off: #393
=> Improve langvis rendering 

code/mouseselection/solutions/de.itemis.mps.selection.runtime/models/de/itemis/mps/selection/runtime/mouse.mps, code/mouseselection/solutions/de.itemis.mps.selection.runtime/models/de/itemis/mps/selection/runtime/plugin.mps
- If the mouseSelection plugin (for some reason) loads after an editor was opened, it didn't get installed into that editor so far. Switching to the EditorExtension API for installing resolved that issue
- when trying to click somewhere to place the cursor, it sometimes happens that we move a few pixels between press and release (by accident). The selection plugin now only considers drags that go further than 2 pixels as the intention to select something
This is a backport since we needed to fix it for an MPS 2019.3 project. A forward port with a PR to `master` will follow.
And I built it together with @slisson , so we can consider it reviewed.
=> MouseSelection: Use EditorExtension API and ignore drags < 2px

code/.mps/modules.xml, code/richtext/languages/richtext/languageModels/behavior.mps, code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/selection.mps
Pasting in richtext while text is selected behaved differently than intuitively expected  from text editors.
In particular:
- When text withing a single word (i.e. part of a string without spaces, not the Word concept) was selected, pasting did not delete the selected text, but simply insert the clipboard text at the caret position
- When multiple words within a Word were selected, pasting did not deselect that text, and the caret position was not moved to the end of the pasted text
This fixes these problems.
=> Richtext: Improve pasting over selection

code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/selection.mps
For cut/delete actions on a richtext selection there was an exception caused by an attempt to start command inside of a read action. This PR fixes that problem by running command as postponed in EDT.
=> richtext: fixed cut/delete actions on selections

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com.mbeddr.mpsutil.grammarcells.intentions.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/generatorutils.mps
In the override behavior is required, but will not break the action
generation, the language designer can now disable the inlining for
individual editor component usages.
(cherry picked from commit 6e1fd46b17c5b5c0be8322ae5f1a60631238ed94)
#423
=> GrammarCells: Allow to disable component inlining (MPS 2021.1)

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com.mbeddr.mpsutil.grammarcells.intentions.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/generatorutils.mps
In the override behavior is required, but will not break the action generation, the language designer can now disable the inlining for individual editor component usages.
#423
=> GrammarCells: Allow to disable component inlining (MPS 2020.3)

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/com.mbeddr.mpsutil.grammarcells.sandboxlang.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/constraints.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com.mbeddr.mpsutil.grammarcells.migration.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/constraints.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/generatorutils.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/com.mbeddr.mpsutil.grammarcells.runtime.msd, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime/menu.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/models/com/mbeddr/mpsutil/grammarcells/tests@tests.mps
When grammar cells were implemented, transformation actions were part of the actions aspect. Later MPS introduced a new transformation menu language as part of the editor. The most relevant change is that the actions aspect doesn't have access to editor while the new transformation language does.
The goal of this PR is not just to use the transformation language in the generator, but to improve the grammar cells behavior by using information available in the editor. The first step was to introduce new high level concepts that don't just make the implementation easier, but can also be used by language developers directly.
As a replacement for left and right transformations there are now the new "before" and "after" transformations. While left/right transformations only show the …
=> Grammar cells migration to the transformation menu language

docs/extensions/all.md, mkdocs.yml
- Adds a new entry "Full  Extension List" to the menu "Extensions".
- Lists all the extensions in the form of tables sorted into categories. The first columns contain the package names, the second column contains  short descriptions.
=> Add Full Extension List

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/solutions/de.itemis.mps.modelmerger.runtime/models/plugin.mps, code/solutions/tests.de.itemis.mps.modelmerger/models/basictest@tests.mps, code/solutions/tests.de.itemis.mps.modelmerger/tests.de.itemis.mps.modelmerger.msd
This PR adds a test case that fails before applying the fix to correct the insertion behavior of the incremental model merger.
If the first node in a child list in the imported model is an unmatched node (i.e., does not appear in the original parent's child listl) then the first node is inserted at the end of the child list. The expectation is that it would be inserted at the start of the list.
This PR adds a check whether it is indeed the first unmatched node, and if there are any unmatched nodes, it simply adds the new node before the first node of the child list.
=> Bug fix for fringe case in incremental model merger

code/math/languages/de.itemis.mps.editor.math/generator/template/main@generator.mps, code/math/solutions/de.itemis.mps.editor.math.runtime/models/de/itemis/mps/editor/math/runtime.mps
Antialiasing was only enabled for math symbols. EditorCellModels such as
math.sqrt didn't use antialising prior to this commit. Fixes IETS3/iets3.opensource#365
=> Enable antialiasing in all math editor cell models

code/langvis/solutions/com.dslfoundry.langvis.plugin/models/com.dslfoundry.langvis.plugin.plugin.mps
When plantuml is not installed, the mps-langvis plugin reports this using a (modal) dialog.
This causes a "AWT events are not allowed inside write action" exception to be triggered.
The issue was originally reported on youtrack: https://youtrack.jetbrains.com/issue/MPS-34018:
I am not aware what would be the write action, because the langvis plugin should not be changing the model. 
A dialog was spawned for a tool invocation, but I am not aware of it changing the model.
This looks like a false positive on the detection of a write action.
However, the change in this pull request will anyway report this error using a "message error" statement, which is more in line with the error reporting in the rest of the plugin. Besides more consistent handling, it would prevent these exceptions being …
=> Fixed: displaying error dialog in mps-langvis causes exception

code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
This fixes tooltips with ref cells in tables.
When a table contains a tooltip that contains a ref cell, the tooltip has null substituteInfo and the grid cell would therefore provide it with its GridSubstituteInfo. But since the tooltip is a transparent collection, it would forward the GridSubstituteInfo to the ref cell, overriding its SReferenceSubstituteInfo with it, which is undesirable.
=> Grid cells now account for transparent collections when adjusting the menu of the cell they wrap

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/com.mbeddr.mpsutil.treenotation.runtime.msd, code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps, code/treenotation/com.mbeddr.mpsutil.treenotation.sandbox/models/com/mbeddr/mpsutil/treenotation/sandbox.mps, code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/com.mbeddr.mpsutil.treenotation.sandboxlang.mpl, code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/models/editor.mps, code/treenotation/com.mbeddr.mpsutil.treenotation.sandboxlang/models/structure.mps, code/treenotation/com.mbeddr.mpsutil.treenotation/com.mbeddr.mpsutil.treenotation.mpl, code/treenotation/com.mbeddr.mpsutil.treenotation/generator/template/main@generator.mps, code/treenotation/com.mbeddr.mpsutil.treenotation/models/behavior.mps, code/treenotation/com.mbeddr.mpsutil.treenotation/models/editor.mps, code/treenotation/com.mbeddr.mpsutil.treenotation/models/structure.mps
This solves issue #481. It consists of the following extensions / changes:
- a new insert handler for treenotation editors named `generic` which allows adding arbitrary runtime `IInsertHandler` instances
- a new runtime class `DefaultInsertHandler` which can be used or adapted
- the `subconcepts` insert handler has been implemented as special case of `generic`
- extended examples to show and test the new features
Here is an example of `generic` usage which behaves like `subconcepts`, but only allows to insert concepts which have an alias:
=> Implement generic insert handler for treenotation

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/typesystem.mps
The issue reported by this checking rule is actually not something which can be fixed by the user. It's just an information that editor component overrides will not work if grammarcells are being used (because the grammarcells generator will always inline components).
=> Replace "Will be inlined. Override will not work." warning by info.

code/.mps/modules.xml
I think it was accidentally removed in the model merger PR.
=> Add back collections lib entry in modules.xml

model-api/build.gradle
I changed the JavaScript compiler for the model-api to use the new `IR` [compiler backend](https://kotlinlang.org/docs/js-ir-compiler.html). The IR compiler can produce better code for interoperability with TypeScript and JavaScript. We are creating an implementation for the INode interface that is consumed from TypeScript. (Not using the modelix model server as a storage backend but a custom implementation.)
Or implementation is a kotlin multiplatform project targeting the JVM and JS. Since we would like to provide our implementation to teams using type script we want to export richt type information for type script tooling, hence are planning to use the IR compiler backend. Unfortunately all dependencies are required to use the IR backend as well otherwise the dependency is rejected …
=> model client use ir compiler

code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/jackson/solutions/com.fasterxml.jackson/com.fasterxml.jackson.msd
The stubs were not working anymore since probably 2021.1.4. Note: The paths change again in 2021.1.5.
=> Fix jackson stubs

model-api/build.gradle
Given Modelix is using the legacy JS compiler it is useful to have support in model-api both for the IR and the legacy Kotlin compiler.
Also, we do not need to generate executables for the model-api, only a library.
=> Setting the BOTH flag for the Kotlin JS compiler

code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
* SModelAsNode supports removing dependencies
* SingleLanguageDependencyAsNode has two new getters
* IChildAccessor supports adding and removing elements
* TreeElementAsNode.setPropertyValue delegate to the property accessor instead of throwing UnsupportedOperationException
=> Refinements of mps adapters

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
Applied same versioning schema for org.apache.commons plugin as used as for all other plugins.
Tbh. I am not sure if the already existing versionNumber should be applied to all plugins or only for plugins that ship languages (not only stubs). In case I am wrong, please let me know.
=> build: updated apache.commons plugin version

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/com.mbeddr.mpsutil.grammarcells.sandboxlang.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com.mbeddr.mpsutil.grammarcells.migration.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/behavior.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime/menu.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps
This PR adds support for an optional description in flag, substitute cells and some other cells such as side transformation cells. When no description is provided, the concept description is used. If the description is empty, the name of the concept is used. Additionally, a wrapped concept parameter for the optional description of the wrapper cell was added.
=> GrammarCells: Add support for descriptions in more cells

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
This PR at least partly fixes https://github.com/JetBrains/MPS-extensions/issues/91 and the following issues:
When dragging an element (or using the arrow keys) to the left/top of the diagram, the diagram normally gets extended and the move preview didn't respect the new translation of the diagram view. In addition, these elements appeared outside the diagram when pressing the reset scale and transform button because of issues with negative coordinates.
Now, this should work in addition to moving the full subdiagram instead of moving an element of the subdiagram to an arbitrary location in the diagram to keep the element within the subdiagram's boundary. When dragging the element to the left or bottom of the diagram, the width/height of the subdiagram gets automatically extended. …
=> diagram: fixes for diagram issues related to dragging elements outside of their parent's boundary

code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime.mps, code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
There where some minor changes made by commit https://github.com/mbeddr/mbeddr.core/commit/3cf328905bf5d62e2b18ad04eb45e5ba4c542a99 in MPS version 2019.3,
which were not moved from mbeddr.core repository.
Affected are BL-classes from the _projectview_
- `CustomTreeNodesUpdater`
- `ProjectViewManager`
Changes are transferred by hand with original commit-message.
(Fork synchronized on 26th October 2022 21:30)
=> ProjectView minor changes from mbeddr "maintenance/mps20193-seca"

code/widgets/languages/de.itemis.mps.editor.enumeration/runtime/models/de.itemis.mps.editor.enumeration.runtime.mps
Exception occurs when trying to take a screenshot of the checkbox since the thread situation is rather unusual in that case.
Stack trace:
```
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1539)
at de.itemis.mps.editor.enumeration.runtime.EnumerationCheckboxImages.updateSize(EnumerationCheckboxImages.java:97)
at de.itemis.mps.editor.enumeration.runtime.EnumerationCheckboxImages$1.imageUpdate(EnumerationCheckboxImages.java:32)
at java.desktop/sun.awt.image.ImageWatched$WeakLink.lambda$update$0(ImageWatched.java:144)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.awt.image.ImageWatched$WeakLink.update(ImageWatched.java: …
```
=> Fix possible ConcurrentModificationException related to checkbox images

code/diagram/languages/de.itemis.mps.editor.diagram.demo.activity/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/models/test/de/itemis/mps/editor/diagram/solution@tests.mps
Fixes #240 The layouter now also runs in the background and can be canceled in the right bottom corner.
I've also removed the multiple calls to the layouter as this code is probably not needed anymore.
Two open questions:
- Should the layouting be really done automatically, or should there be a setting in the editor to enable/disable it?
- Do we need a configurable timeout for the layouting? In the past, the layouter froze the editor but now it might be a non-issue.
=> diagram: run autolayouter if no layout data exist and run layouter in background

code/.mps/modules.xml, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/com.mbeddr.mpsutil.intentions.sandboxlang.mpl, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/generator/templates/com.mbeddr.mpsutil.intentions.sandboxlang.templates@generator.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.behavior.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.constraints.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.editor.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.structure.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.typesystem.mps, code/solutions/com.mbeddr.mpsutil.intentions.sandbox/com.mbeddr.mpsutil.intentions.sandbox.msd, code/solutions/com.mbeddr.mpsutil.intentions.sandbox/models/com.mbeddr.mpsutil.intentions.sandbox.sandbox.mps
This PR trims the group name from grouped entries without submenu
When intention groups are used, the groupname is derived from the intention-names group-name-prefix (e.g. `"Some Group:" + " DemoIntention_1"`) or the intention-group annotation. Furthermore the intention is transformed to contain submenus. During this process the group-name-prefix is trimmed from the intention-name. 
If an intention doesn't contain a submenu, this trimming is missed, thus the group-name-prefix is shown on each intention in the group.
After the groupname was derived from the intention-name, in the case where the intention doesn't contain a submenu, the groupname and the `:` is trimmed from that intentions name.
For easier testing, I've created the branch …
=> Intentions: Trim group name from grouped entries without submenu

code/.mps/modules.xml, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell.demolang/de.itemis.mps.editor.htmlcell.demolang.mpl, code/htmlcell/languages/de.itemis.mps.editor.htmlcell.demolang/models/de.itemis.mps.editor.htmlcell.demolang.editor.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell.demolang/models/de.itemis.mps.editor.htmlcell.demolang.structure.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell.demolang/resources/html_3.2_demo.html, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/de.itemis.mps.editor.htmlcell.mpl, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/generator/templates/de.itemis.mps.editor.htmlcell.generator.templates@generator.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/models/de.itemis.mps.editor.htmlcell.behavior.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/models/de.itemis.mps.editor.htmlcell.editor.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/models/de.itemis.mps.editor.htmlcell.structure.mps, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/sandbox/de.itemis.mps.editor.htmlcell.sandbox.msd, code/htmlcell/languages/de.itemis.mps.editor.htmlcell/sandbox/models/de.itemis.mps.editor.htmlcell.sandbox.mps, code/htmlcell/solutions/de.itemis.mps.editor.htmlcell.runtime/de.itemis.mps.editor.htmlcell.runtime.msd, code/htmlcell/solutions/de.itemis.mps.editor.htmlcell.runtime/models/de.itemis.mps.editor.htmlcell.runtime.runtime.mps
As part of a performance investigation, I've created this experimental custom swing component that supports a small subset of HTML. With a few additional lines there could also be rudimentary support for [RTF](https://en.wikipedia.org/wiki/Rich_Text_Format) in case anybody needs that. This cell can be used, for example, for long read-only explanations instead of using many single MSP editor cells.
Unfortunately,I couldn't quite figure out the correct relayouting of the cell. I think there might still be issues where the content of the JComponent gets cuts off on the right side, that's why the PR is still in draft mode.
Not sure if we really need it, as it doesn't integrate that nicely with other editor cells and using some old HTML standard for writing messages is also not that great. At …
=> Feature: HTML Swing-Component

code/diagram/languages/de.itemis.mps.editor.diagram.demolang/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram.demolang/languageModels/structure.mps, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.sandbox/models/de/itemis/mps/editor/diagram/sandbox.mps
Original problem: When the layout data of a diagram with sub-diagrams is changed (e.g. auto-relayout), each diagram saves its own layout data, which means that multiple root nodes might be affected by a change. This PR adds a new option to save the layout data of sub-diagrams in the same location as the main diagram.
The option is not enabled by default. It can be enabled in the properties of the diagram cell:
If there are multiple sub-diagram layers, this option has to be enabled for each sub-diagram.
=> Diagrams: give the option to save the layout data of subdiagrams in the main diagram

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/languageModels/editor.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/languageModels/structure.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps, code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/models/test/de/itemis/mps/editor/diagram/solution@tests.mps, code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/test.de.itemis.mps.editor.diagram.solution.msd
This PR adds a new field to the diagram editor to customize the behavior when the layout of a diagram is stored in the layout map variable. 
The field is a function that takes as input an editor context and a node, and returns a boolean value. If the value is true, the layout is stored in the layout map, if it is false, no layout is stored.
A small test that ensures that no layout is stored is included in the diagram tests.
=> Add an editor field to customize layout storing of diagrams

requirements.txt
This is now possible due to a few build agents having a high enough Python version installed. I've restricted the suitable agents in the build configuration.
=> Update mkdocs-material to latest version

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
This PR adds a boolean override flag to the `saveDiagramLayout` function.
If it is set to true, the diagram layout is stored, no matter how the saving is configured  in the diagram editor. This allows properly storing layouts via user-intentions.
=> Allow overriding layout storing

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
Projects including MPS.ThirdParty as a build dependency were failing compilation because of missing platform_lib/app.jar file.
This PR addresses this issue.
=> Fix platform_lib app.jar not being found in dependencies

build.gradle
Fixes #630 by using major/minor version number in local build.
=> Fix wrong version number for local build (#630)

build.gradle, settings.gradle
- Backported from 21.3:  see https://github.com/JetBrains/MPS-extensions/pull/646
- Fixed the `checkModulePaths`-gradle task, so correct paths are used on windows machines
(Since the `rootDirectory` variable contains the path with windows file-separators and `replaceAll()` uses a regex, all the windows-file-separators are dismissed, leading to wrong paths for all modules in the modules.xml. The regular `replace()` does the same replacement, but without the regex, keeping the windows-file-separators in place. Because the separators are still used based on the OS, this will not influence other OS.)
- Backported  from 21.3:  see https://github.com/JetBrains/MPS-extensions/pull/651
=> Fixing build

CHANGELOG.md, code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/constraints.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/com.mbeddr.mpsutil.grammarcells.runtime.msd, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.sandbox/models/com/mbeddr/mpsutil/editor/cells/sandbox.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/com.mbeddr.mpsutil.grammarcells.tests.msd, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/models/com/mbeddr/mpsutil/grammarcells/tests@tests.mps
Previously, if concept `A` contained concept `B` with an editor defined with grammar.rule with a grammar.wrap for `B`, constraints from `A` limiting occurrences of `B` were not taken into account when building the completion menu items. 
This PR fixes this issue.
The PR is a breaking change because it alters completion menus for all concepts that fall under the above description.
Fixes #641.
=> [Breaking] Extend grammar.wrap to check constraints properly

.github/workflows/PR-into-2022-2.yml
Adapted from https://github.com/modelix/modelix.mps/blob/mps/2022.2/.github/workflows/PR-into-2022-2.yml
Should create a merge PR for the 2022.2 branch whenever a PR is merged into this branch.
=> GitHub workflow to merge this branch into 2022.2

.github/workflows/PR-into-2022-2.yml, .github/workflows/PR-into-next-version.yml
An attempt to make the cascading PR workflow reusable so that it doesn't have to be copied-and-pasted for each new version.
=> Reusable workflow for cascading merges

.gitignore, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps, code/model-api/test.org.modelix.model.mpsadapters/models/test.org.modelix.model.mpsadapters.wrappingmodelapi@tests.mps
Switches the default compiler to IntelliJ (`<javac2>` Ant task). Javac2 instruments code to ensure that `@NotNull` variables are never null at run time.
This is a breaking change because code that used to work before may start throwing exceptions now. However, it is likely that such code didn't work before anyway and it will now throw exceptions earlier in the call stack.
=> [breaking] Enforce @NotNull annotations at runtime

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/constraints.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/editor.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/models/com/mbeddr/mpsutil/grammarcells/tests@tests.mps
The changes from #664 were causing some completion menus to become empty since the constraints were not set up to check for abstract dummy nodes. This PR addresses this issue by moving the earlier constraint test back to its original version. The filtering is then performed when building the concrete action list.
=> Update GrammarCells constraint checks to fix empty completion menus

code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/com.mbeddr.mpsutil.grammarcells.mpl
It causes warnings in the log during generation.
=> Remove generator priority rule referring to nonexistent mapping

CHANGELOG.md, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
Previously, if a model node had an attribute annotation and is used as an edge in a diagram, the attribute editor would be added as an _external box_ in the diagram (also see example node `R1` in the repo):
In this picture, the annotation `Component Annotation` is floating around in the diagram. Auto-layouting also does not work.
This PR adds support for pulling these annotations into the edge labels:
The key difference is that in the new setting, the annotation is part of the edge label and thus also automatically layouted.
To apply this change, the PR adds a new flag `pullAnnotations` as a boolean query over the node and the editor context. The standard behavior from above is retained by leaving it at the default `false` value.
This work was done jointly with @slisson.
=> Add a new flag to pull attribute editors into edge labels

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/com.mbeddr.mpsutil.intentions.runtime.msd, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/editor.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/com.mbeddr.mpsutil.intentions.sandboxlang.mpl, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.editor.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.structure.mps, code/solutions/com.mbeddr.mpsutil.intentions.sandbox/models/com.mbeddr.mpsutil.intentions.sandbox.sandbox.mps, docs/extensions/utils/intentions-menu.md
The main idea is to still allow the intention menu even if nodes are, for example, just projected into the editor through a query list and read-only.
I've tried to add tests but couldn't find a way to test this. The `invoke intention` statement in the editor test doesn't check if the cell is read-only and trying to invoke a demo intention through actions or key presses also didn't work.
=> mpsutil.intentions: add a new style attribute to allow intentions in read-only-cells

code/diagram/solutions/de.itemis.mps.editor.diagram.demoentities.sandbox/models/de/itemis/mps/editor/diagram/demoentities/sandbox.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps
Previously, pressing Ctrl+A in a diagram label would select every node up until the including root node.
This PR adds a new plugin that fixes this issue. The key functionality was provided by @slisson, I have only fixed remaining bugs.
The last selection in the video below shows the limitations of the plugin, where only label cells are supported currently.
=> Extend diagrams with a select-all plugin

code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps
When cells with our own layout algorithm were mixed with the default MPS layouter then cells were overlapping especially if the content was bigger than the configured "Text width".
Now, if we replace the layouter somewhere, it is replaced in the whole subtree.
=> fix(celllayout): cells where overlapping in some cases

CHANGELOG.md, code/tables/languages/de.slisson.mps.tables.demolang/languageModels/editor.mps, code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps, code/tables/languages/de.slisson.mps.tables/languageModels/editor.mps, code/tables/languages/de.slisson.mps.tables/languageModels/structure.mps, code/tables/languages/de.slisson.mps.tables/runtime/de.slisson.mps.tables.runtime.msd, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/plugin.mps, docs/extensions/editor/tables.md
Tables now support a new property _row UI actions (experimental)_: This property adds actions to the MPS toolbar to add a new row above (up arrow)/below(down arrow) the current row or to delete the current row (x). These actions only work for simple tables that are based on rows. The property is set to false by default.
=> tables: initial support for row actions

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
This PR reverts https://github.com/JetBrains/MPS-extensions/pull/629 and fixes it properly (the change is in the inspector).
The issue was that when you used `MPS.ThirdParty` in a different project and have MPS-Extensions as a dependency, you got the exception (example from mbeddr.core):
`
path $(platform_lib)/app.jar was not found in the layout
--- --- was input node: [modules] BuildMps_Language "com.mbeddr.mpsutil.json" in com.mbeddr.mpsutil.dev.build
` 
I've opened MPS-Extensions and mbeddr.core and tried to rebuild the [com.mbeddr.platform](http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F4160126263863194133) build script and it seems to work.
=> Don't export app.jar in the layout and map the dependencies correctly

CHANGELOG.md
The problem was reproducible by dropping elements from the palette. An example of broken ports can be seen here:
The problem is that ports don't always have the correct size from the parent cell for positioning them:
I am correcting the size of the parent cell now before layouting the ports. In the past, we just run the layouter 5 times. We still have issues with ports that are on the south side and when resizing cells with ports where the ports are at the wrong location:
=> Fix size of parent cell before layouting the ports

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/com.mbeddr.mpsutil.intentions.runtime.msd, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/editor.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/intentions.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/structure.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps
This is a follow-up of https://github.com/JetBrains/MPS-extensions/pull/691: Intentions in read-only cells can now be disabled by adding this annotation to an intention declaration and setting the flag to true.
=> mpsutil.intentions: Add an annotation "Toggle Show Intention In Read-Only Cell"

CHANGELOG.md, code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cells.mps, code/richtext/languages/javadoc/languageModels/structure.mps, code/richtext/languages/richtext/languageModels/editor.mps, code/richtext/languages/richtext/models/de/slisson/mps/richtext/runtime.mps, docs/extensions/editor/richtext.md
The code completion entries of word cells are now clearer and unnecessary entries were removed.
Edit: I am not so sure about the second code completion entry. Do we really need this functionality? It inserts the entry at the current cursor position instead of replacing everything below the cursor. I've tried to add an explanation to the description but it still looks confusing:
=> Better word cell code completion entries

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/de.itemis.mps.editor.celllayout.mpl, code/celllayout/languages/de.itemis.mps.editor.celllayout/generator/template/main@generator.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/behavior.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/constraints.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/de.itemis.mps.editor.celllayout.intentions.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/editor.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/structure.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout/models/typesystem.mps, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/de.itemis.mps.editor.celllayout.runtime.msd, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime/plugin.mps
- A new action `Copy Cell Reference` is available in the editor menu in `Language Debug` that creates a reference to the current select editor cell. It can be pasted into the MPS console to debug editor cells. It can be activated through ctrl/cmd+alt+c.
- A new action `Copy Editor Component Reference` is available in the editor menu in `Language Debug` that creates a reference to the current editor component. It can be pasted into the MPS console to debug editor cells. To refer to the currently opened editor component, use the expression `#currentEditorComponent` in the MPS console.
Remark: The references stop working when the corresponding editor is closed or reopened because they use the hashcode of the editor component.
Examples:
```java …
```
=> Editor Cell and Editor Component references for the MPS console

code/math/solutions/de.itemis.mps.editor.math.runtime/models/de/itemis/mps/editor/math/runtime.mps
The old condition is not present in the original MPS [MoveLeft](https://github.com/JetBrains/MPS/blob/8b25a6915d8b3e03a496e64143654e4cd279f1a2/editor/editor-runtime/source/jetbrains/mps/nodeEditor/NodeEditorActions.java#L119) implementation and there is no reason to restrict the code to editor cell labels. Example: Moving to a vertical bar after a math cell which can be implemented as a basic editor cell.
=> Allow moving to arbitrary cells from math cells

CHANGELOG.md, code/modellisteners/com.mbeddr.mpsutil.modellisteners.runtime/models/com/mbeddr/mpsutil/modellisteners/runtime.mps, code/modellisteners/com.mbeddr.mpsutil.modellisteners/generator/template/main@generator.mps
It is not required anymore to regenerate the listener aspect after the interface support was introduced in https://github.com/JetBrains/MPS-extensions/pull/694.
=> modellisteners: make the interface support change backward compatible

build.gradle
Necessary to run tests on macOS until JetBrains/MPS#71 is fixed.
=> Patch JNA path in build scripts

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
We are using diagrams imbricated in other diagrams (sub-diagrams), 
The layout information for a subdiagram is already read when the object SubdiagramECell is created
The ModelSynchronizer reads from SModel unnecessarily many times - this triggers many calls for imbricated diagrams.
This PR removes the reccursive refreshing of sub-diagrams from model:
=> diagram.runtime.model: ModelSynchronizer - avoid unnecessary calls to fromSModel_Subdiagram for sub-diagrams

CHANGELOG.md, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps
With `save layout data` set to false, some information was lost and for example, some ports were placed incorrectly when the diagram was redrawn. This PR also applies the additional fix from https://github.com/JetBrains/MPS-extensions/pull/761. Maybe we can get rid of this workaround in the future.
=> Save diagram layout cache in user object

CHANGELOG.md, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps, code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.tests/models/com/mbeddr/mpsutil/grammarcells/tests@tests.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.structure.mps, code/model-api/test.org.modelix.model.mpsadapters/models/test.org.modelix.model.mpsadapters.wrappingmodelapi@tests.mps, code/pagination/languages/de.itemis.mps.editor.pagination.demolang/models/de.itemis.mps.editor.pagination.demolang.structure.mps, code/pagination/languages/de.itemis.mps.editor.pagination/models/de.itemis.mps.editor.pagination.plugin.mps, code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.pages.mps, code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.plugin.utils.mps, code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.ui.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/structure.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com/mbeddr/mpsutil/editor/querylist/runtime.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.sandbox/models/com/mbeddr/mpsutil/editor/querylist/sandbox.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/structure.mps, code/statistics/models/de.itemis.mps.statistics.plugin.mps, code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/plugin.mps
Dynamic generated nodes (without a model) can now be used in query lists if `read-only` is set to true.
All other actions like inserting nodes, deleting etc. won't work when the cell is not read-only because the node is not attached to any model.
=> com.mbeddr.mpsutil.editor.querylist: Add support for dynamic content in querylists

CHANGELOG.md, code/.mps/modules.xml, code/blutil/languages/com.mbeddr.mpsutil.blutil/blutil.mpl, code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/migration.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/structure.mps, code/blutil/tests/test.com.mbeddr.mpsutil.blutil.doc/models/test.com.mbeddr.mpsutil.blutil.doc@tests.mps, code/blutil/tests/test.com.mbeddr.mpsutil.blutil.doc/test.com.mbeddr.mpsutil.blutil.doc.msd, code/blutil/tests/test.ts.match/models/main@tests.mps, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps
`MethodLineDoc` is not needed anymore, that's why I have marked it as deprecated. It is heavily used in mbeddr.core. There are replacement concepts in `jetbrains.mps.baseLanguage.javadoc`. `BLDoc` can only partly be migrated because there is no equivalent concept to attach documentation to any node, that's why I hav not marked it as deprecated. I've written migrations for all the cases that are possible to migrate. Especially with `BLDoc` only migrations with text content are possible because there is no 1:1 mapping between the rich text and text language.
=> mpsutil.blutil: deprecate MethodLineDoc + migrate BLDoc if possible

code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/third-party/solutions/MPS.ThirdParty/MPS.ThirdParty.msd, code/third-party/solutions/third.party.usage.test/models/third.party.usage.test.mdl.mps, code/third-party/solutions/third.party.usage.test/third.party.usage.test.msd
This PR fixes #789 
The changes made, are based on the  current module properties configuration and packaging of the JAXB module solution. 
**Changes are**
- MPS.Thirdparty is confiured as an intellij plugin with the id `"com.intellij"`
- stubModelEntry and modelRoot are resolved via the `${platform_lib}` path
- Packaging was done the same way it is done for [JAXB](http://127.0.0.1:63320/node?ref=r%3A874d959d-e3b4-4d04-b931-ca849af130dd%28jetbrains.mps.ide.build%29%2F7972607346140852471)
**Simple Test**
- in addition I've added a simple test scenario
- We now have solution that uses some BL classes provided by MPS.Thirdparty
- This solution is part of the test build conflig and should be generated and compiled during CL build
- in case we have classloading issues, its compilation will …
=> MPS.Thirdparty: Fixed classloading issue due to wrong packaging 

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/celllayout/solutions/de.itemis.mps.editor.celllayout.sandbox/de.itemis.mps.editor.celllayout.sandbox.msd, code/conditional-editor/languages/de.slisson.mps.conditionalEditor.demolang/languageModels/editor.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor.demolang/languageModels/structure.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/de.slisson.mps.conditionalEditor.mpl, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/generator/template/main@generator.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/languageModels/behavior.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/languageModels/constraints.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/languageModels/editor.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/languageModels/structure.mps, code/conditional-editor/languages/de.slisson.mps.conditionalEditor/languageModels/typesystem.mps, code/conditional-editor/solutions/de.slisson.mps.conditionalEditor.sandbox/models/de/slisson/mps/conditionalEditor/sandbox.mps
The parameter information is saved in the user object of the node instead of the root editor cell. The reason is that on first editor creation, this information can't be accessed.
For updated screenshots: see last answer
=> Implement editor components with parameters

build.gradle
This is of course already working on the TC but we also need to enable it in the build script so that artifacts are not published when tests are failing.
=> Fail build when a test fails

CHANGELOG.md, code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime.mps, code/projectview/com.mbeddr.mpsutil.projectview/languageModels/editor.mps
The custom project views couldn't be reloaded because adding the updated project views happened before the removal of the old project views.
=> mpsutil.projectview: Fix project view reloading

code/grammarcells/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps, code/multiline/solutions/de.slisson.mps.editor.multiline.runtime/models/de/slisson/mps/editor/multiline/cellProviders.mps, code/widgets/languages/de.itemis.mps.editor.enumeration/runtime/models/de.itemis.mps.editor.enumeration.runtime.mps, code/widgets/solutions/de.itemis.mps.editor.bool.runtime/models/de/itemis/mps/editor/bool/runtime.mps
It can happen when showing dynamically generated nodes in query lists that the model is null.
=> Set the the read-only flag in all property cell providers if the model is null

code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/migration.mps, scripts/build.xml
The implementation uses magic constants for the MigrationTestCase input/outputNodes containment links to avoid adding a dependency on jetbrains.mps.lang.test language.
=> blutil: avoid migrating input/output nodes of MigrationTestCase

CHANGELOG.md, build.gradle, code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/changelog/de.itemis.mps.changelog.sandbox/de.itemis.mps.changelog.sandbox.msd, code/changelog/de.itemis.mps.changelog.sandbox/models/de.itemis.mps.changelog.sandbox.mps, code/changelog/de.itemis.mps.changelog/de.itemis.mps.changelog.mpl, code/changelog/de.itemis.mps.changelog/generator/templates/de.itemis.mps.changelog.generator@generator.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.behavior.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.constraints.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.editor.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.intentions.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.structure.mps, code/changelog/de.itemis.mps.changelog/models/de.itemis.mps.changelog.typesystem.mps, code/changelog/de.itemis.mps.changelog/sandbox/de.itemis.mps.changelog.sandbox.msd, code/changelog/de.itemis.mps.changelog/sandbox/models/de.itemis.mps.changelog.sandbox.mps, code/solutions/de.itemis.mps.extensions.changelog/de.itemis.mps.extensions.changelog.msd, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
It is based on `jetbrains.mps.lang.text` and not `de.slisson.mps.richtext` and uses `com.dslfoundry.plaintextflow` for generating the Markdown file. There is some additional documentation in the inspector of the _Changelog_ concept:
The generated file is currently copied to the root directory with the Gradle task _copyReadme_ which should be improved. The language supports the change headers _formats version + date_ and _month + year_:
**First format:**
**Second format:**
=> Add a language to describe CHANGELOG.md files

CHANGELOG.md, code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/behavior.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/typesystem.mps
The automatically applied quick fix sometimes doesn't work as intended and the editor starts flickering (maybe the type calculation is non-deterministic, I couldn't reproduce it). The element's concept can now be set on your own risk. It is used in different places in MPS but doesn't seem critical to me.
=> com.mbeddr.mpsutil.editor.querylist: don't force the element's concept

code/conditional-editor/languages/de.slisson.mps.conditionalEditor/generator/template/main@generator.mps
=> mps.conditionalEditor: removed broken model dep. in generator model

code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
ModulePath is internal data structure; with ProjectBase.getVirtualFolder available since 2022, no need to use one.
=> Use Project API to access module's virtual folder

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps
This fixes the issue with the missing embedded fonts in the exported diagrams.
=> editor.diagram: use the context for the svg generation

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/typesystem.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/com.mbeddr.mpsutil.editor.querylist.runtime.msd, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com.mbeddr.mpsutil.editor.querylist.runtime.plugin.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Found another performance issue with querylist model checking: It doesn't preserve the `TypeCheckingContext.NonTypesystemComputationMode`. If we have (expensive) checks marked as `do not apply on the fly: true`, they were still executed by querylist.
Unfortunately, I didn't find a better way than to duplicate most of `NonTypesystemChecker.getErrors()`.
=> keep typesystem checker computation mode alive inside querylist

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/de.itemis.mps.editor.celllayout.runtime.msd, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime/plugin.mps, code/hacks/solutions/de.slisson.mps.hacks.editor/models/de/slisson/mps/hacks/editor.mps, code/tooltips/solutions/de.itemis.mps.tooltips.runtime/models/de/itemis/mps/tooltips/runtime/plugin.mps, code/widgets/solutions/de.itemis.mps.mouselistener.runtime/de.itemis.mps.mouselistener.runtime.msd, code/widgets/solutions/de.itemis.mps.mouselistener.runtime/models/de/itemis/mps/mouselistener/runtime/plugin.mps
Since 2024.1, MPS EditorExtensionRegistry become a CoreComponent (used to be IDEA ProjectComponent).
To access both IDEA and MPS components, use MPSProject.getComponent() API.
Note, this approach is necessary for compatibility between MPS 2024.1 and earlier versions as long as same MPS-extensions code is in use both in 2023.x and 24.x versions. Once there's 24.1+ only (23.3 forks to maintenance), `ProjectPlugin` parts contributing EditorExtension shall get converted into `ApplicationPlugin`, as EditorExtensionRegistry CoreComponent is application-wide (unlike IDEA's ProjectComponent it used to be up and including to 2023.3).
=> Fix EditorComponentCreationListener uses

code/projectview/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
In 24.2, MPS replaced IDEA AppComponent with a service.
ReloadManager.getInstance() has been introduced back in 22.3, works fine for both (component and service) implementations.
=> Access ReloadManager impl through interface and getInstance()

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/de.itemis.mps.editor.diagram.demoentities.mpl, code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/languageModels/structure.mps, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/behavior.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/languageModels/behavior.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/languageModels/editor.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/languageModels/structure.mps, code/diagram/languages/test.de.itemis.mps.editor.diagram.lang/test.de.itemis.mps.editor.diagram.lang.mpl, code/diagram/solutions/de.itemis.mps.editor.diagram.demoentities.sandbox/models/de/itemis/mps/editor/diagram/demoentities/sandbox.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps, code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/models/test/de/itemis/mps/editor/diagram/solution@tests.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
The idea is that you want to sometimes shrink a diagram box to a size below the required size, so that the automatic line wrapping kicks in e.g. with Text from the richtext language. I set the max-width stylesheet item for that. Fit size all and autolayout should respect this setting. @slisson would it be possible to somehow also do this for sizes that are above the minimum size?
=> editor.diagram: add a new option to allow boxes to set a new required minimum size

CHANGELOG.md, code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/de.itemis.mps.editor.diagram.runtime.msd, code/diagram/solutions/test.de.itemis.mps.editor.diagram.solution/models/test/de/itemis/mps/editor/diagram/solution@tests.mps, code/kotlin/solutions/MPS.Kotlin/MPS.Kotlin.msd, code/kotlin/solutions/kotlin.usage.test/kotlin.usage.test.msd, code/kotlin/solutions/kotlin.usage.test/models/kotlin.usage.test.mdl.mps, code/multiline/languages/demolang/languageModels/structure.mps, code/multiline/languages/multiline/languageModels/editor.mps, code/multiline/languages/multiline/languageModels/structure.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/typesystem.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com.mbeddr.mpsutil.editor.querylist.runtime.plugin.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps, code/tables/languages/de.slisson.mps.tables.demolang/languageModels/editor.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps, code/third-party/solutions/third.party.usage.test/third.party.usage.test.msd
The stubs basically contain the Kotlin standard library so that references work when using IntelliJ classes from `MPS.ThirdParty` that reference Kotlin code.
Test file: http://127.0.0.1:63320/node?ref=39983771-4e9b-401b-a1a9-1da6c777c843%2Fjava%3Acom.intellij.openapi.vcs.checkin%28MPS.ThirdParty%2F%29%2F~CommitCheck
(all references should work).
I included the new stubs in a mbeddr build script, and it seems to work fine. I didn't include the workaround for the MPS-ThirdParty stub.
I am not sure about the re-export flags in `MPS.ThirdParty` and `MPS.Kotlin` though.
=> Create Kotlin Java stubs: MPS.Kotlin

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/constraints.mps, code/kotlin/solutions/MPS.Kotlin/MPS.Kotlin.msd, code/kotlin/solutions/kotlin.usage.test/kotlin.usage.test.msd
If MPS.Kotlin depends on MPS.Thirdparty and vice versa, we have a cyclic dependency that can't be resolved in tests. This commit is cherry picked from the last 20232 merge commit where we first saw this issue.
=> only re-export Annotations in MPS.Kotlin

CHANGELOG.md, code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram.styles/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/behavior.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.demoentities.sandbox/models/de/itemis/mps/editor/diagram/demoentities/sandbox.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Diagrams can now show a grid that is used for snapping elements to it. It can be configured (visibility, grid snapping, grid color/size/style) in the editor definition of the diagram itself:
The elements sometimes don't snap to the grid itself but that seems to be an issue in the library itself. Taken from https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/java/src/com/mxgraph/swing/handler/mxGraphHandler.java#L1105: 
> Drag image _size_ depends on the initial position and may sometimes
> not align with the grid when dragging. This is because the rounding of the width
> and height at the initial position may be different than that at the current
> position as the left and bottom side of the shape must align to the grid lines.
>  Only fix is a full repaint of …
=> editor.diagram: add support for grid snapping

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com/mbeddr/mpsutil/editor/querylist/runtime.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/com.mbeddr.mpsutil.editor.querylist.mpl, code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/behavior.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/constraints.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/structure.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/typesystem.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Inside the query, you now have an expression `index` and `node` (previously: `queryListNode`) to refer to the queried node and the index that returns the index in the returned list of nodes.
=> mpsutil.editor.querylist: add support for an index expression

CHANGELOG.md, code/blutil/languages/com.mbeddr.mpsutil.blutil/solutions/com.mbeddr.mpsutil.blutil.rt.msd, code/blutil/languages/com.mbeddr.mpsutil.blutil/solutions/models/com.mbeddr.mpsutil.blutil.rt.scoping.mps, code/blutil/tests/test.com.mbeddr.mpsutil.blutil/models/test.com.mbeddr.mpsutil.blutil.scoping@tests.mps, code/blutil/tests/test.com.mbeddr.mpsutil.blutil/test.com.mbeddr.mpsutil.blutil.msd, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
The new scope class `UniqueElementScope` is a delegating scope which ensures that each element is in the scope only once. 
As this is often used in conjunction with a `CompositeScope`, I added a convenience factory method to create an `UniqueElementScope` object from a set of input scopes.
The PR also adds a couple of tests for the new functionality.
This solves issue #969.
=> Provide new scope class UniqueElementScope

CHANGELOG.md, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps, code/tables/languages/de.slisson.mps.tables.demolang/languageModels/editor.mps, code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/gridmodel.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/plugin.mps, code/tables/solutions/test.de.slisson.mps.tables/models/test/de/slisson/mps/tables@tests.mps
@arimer to test the changes, please have a brief look at the MPS-Extensions [Tables Sandbox](http://127.0.0.1:63320/node?ref=r%3A7b909ba9-e58e-4fbd-8829-ecfbd89930fa%28de.slisson.mps.tables.sandbox%29%2F1397920687866914332) to check for broken stuff. I didn't add any delete or insert handlers there.
For proper testing, you can open https://github.com/IETS3/iets3.opensource/tree/bugfix/tables as a second project and check instances of the following concepts: DataTable, Sheet, LookupTable, DecTab.
When the default implementation for deletion is used (not derived from a header deletion handler), there is a differentiation between BACKSPACE (delete to the left of cursor) and DELETE (delete to the right of the cursor). For the derived delete actions we could create a followup ticket. For …
=> Tables: Various fixes to table end cells in combination with insert and deletion handler

code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/behavior.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/editor.mps, code/blutil/languages/com.mbeddr.mpsutil.blutil/languageModels/structure.mps
The old implementation of named back references didn't work because `MatchParensRegexp#getIndex` has a faulty implementation.
=> mpsutil.blutil: introduce named groups and refer to them from named back references

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/shadowmodels/solutions/de.q60.mps.collections.libs/de.q60.mps.collections.libs.msd
Don't mention model roots for solutions `de.q60.mps.collection.libs` and `de.itemis.stubs.batik`, as they lead to model loading warnings on each MPS startup
=> remove de.q60.mps.collection.libs and de.itemis.stubs.batik model roots

code/shadowmodels/solutions/de.q60.mps.shadowmodels.runtime/models/plugin.mps
This PR is a workaround for non-shadow model users for https://youtrack.jetbrains.com/issue/MPS-37996. If shadow models are activated, the in the ticket mentioned issue still persists.
=> shadowmodels: only activate the logical view extension if shadowmodels are activated

.github/workflows/vulnerability-scanning.yml
Currently, the build won't fail.  We would have to add an argument like --failOnCVSS 7 to fail the build for issues with high severity. For example, for jgraphx we would have to add it as a false positive since we can't update the library.
You can find the output for a run on the actions page: https://github.com/JetBrains/MPS-extensions/actions/runs/12163684040?pr=1075. There is an artifact [Depcheck report](https://github.com/JetBrains/MPS-extensions/actions/runs/12163684040/artifacts/2274387072).
Alternativelly, we could only add it for the `workflow_dispatch` event. Then you would have to call it manually.
=> include a GitHub workflow for vulnerability scanning

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/com.mbeddr.mpsutil.intentions.runtime.msd, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime/plugin.mps
- partly fixes https://github.com/JetBrains/MPS-extensions/issues/1002
The problem is we overwrite `IntentionsSupport#checkAndShowMenu` in https://github.com/JetBrains/MPS-extensions/pull/691, so we still need reflection
=> mpsutil.intentions: rewrite code to use the intention menu producer

code/treenotation/com.mbeddr.mpsutil.treenotation.runtime/models/com/mbeddr/mpsutil/treenotation/runtime.mps
Before:
After:
Sometimes the overlap was even more severe:
=> fix(treenotation): overlapping buttons

code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/plugin.mps, code/pagination/solutions/de.itemis.mps.editor.pagination.runtime/models/de.itemis.mps.editor.pagination.runtime.ui.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
Patch against  maintenance/mps20243 so that we can remove deprecated code in 2025.1
=> Use actual StyleRegistry of an editor instead of singleton

code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps
Based on this line: https://github.com/JetBrains/MPS/blob/master/editor/intentions-runtime/source/jetbrains/mps/editor/intentions/IntentionMenuProducer.java#L152
Otherwise an action that is a popup group is not "performable" in the ordinary sense.
Only affects versions for MPS 2023.2 and higher which have the MyIntentionMenuProducer implementation.
=> Make intentions executable even if they have children, just like in MPS IntentionMenuProducer.

CHANGELOG.md, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
In some cases, the ports were layouted too early and subdiagrams where not considered:
vs
=> editor.diagram: layout ports after initializing subdiagrams

code/modellisteners/com.mbeddr.mpsutil.modellisteners.runtime/models/com/mbeddr/mpsutil/modellisteners/runtime.mps, code/modellisteners/com.mbeddr.mpsutil.modellisteners.sandboxlang/languageModels/listeners.mps
Fixes the exception:
java.lang.AssertionError
at jetbrains.mps.smodel.BaseFastNodeFinder$ConceptNodeMap.forget(BaseFastNodeFinder.java:244)
at jetbrains.mps.smodel.BaseFastNodeFinder.removed(BaseFastNodeFinder.java:83)
at jetbrains.mps.smodel.BaseFastNodeFinder$ChangeTracker.nodeRemoved(BaseFastNodeFinder.java:322)
at jetbrains.mps.smodel.event.ModelEventDispatch.fireNodeRemove(ModelEventDispatch.java:155)
at jetbrains.mps.smodel.AttachedNodeOwner.fireNodeRemove(AttachedNodeOwner.java:319)
at jetbrains.mps.smodel.SNode.removeChild(SNode.java:208)
at jetbrains.mps.smodel.SNode.delete(SNode.java:220)
at jetbrains.mps.nodeEditor.selection.NodeRangeSelection$1.doExecute(NodeRangeSelection.java:327)
at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:55)
at …
=> modellisteners: clear the fast node finder cache when the child is removed

code/widgets/languages/de.itemis.mps.editor.enumeration/runtime/models/de.itemis.mps.editor.enumeration.runtime.mps
Workaround for loading icons for the enumeration checkboxes (`de.itemis..mps.editor.enumeration`) from deployed modules.
The issue has been originally introduced in MPS 2023.3 (https://github.com/JetBrains/MPS/commit/e98d3851ad3504479634a9864d847d4300915879) and there is MPS bug ticket filed for it: https://youtrack.jetbrains.com/issue/MPS-38207/Deployed-module-resouces-cannot-be-loaded-anymore-using-module-macro. Until the issue is addressed on the MPS side, we need to rely on the workaround (possibly needed in other locations, enumeration checkboxes is just one of them required for the successful migration to MPS 2024.1).
=> widgets: workaround to load enum checkbox images from bin.jar instead of src jar

code/shadowmodels/solutions/de.q60.mps.shadowmodels.runtime/models/smodel.mps
Remove Override annotation to get ready for upcoming changes in MPS, where these methods cease to exist
I'm about to push changes into MPS master where these methods are either deleted, moved to another base class or there's a default implementation in EditableModelDescriptor. No annotation helps to have both versions compiled. Once my changes are in master, these methods could get removed from SM_ShadowModel as well
=> EditableSModel: few methods to become history

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/com.mbeddr.mpsutil.editor.querylist.demolang.mpl, code/querylist/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist.runtime/models/com/mbeddr/mpsutil/editor/querylist/runtime.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/generator/template/main@generator.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/behavior.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/constraints.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/editor.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/structure.mps, code/querylist/com.mbeddr.mpsutil.editor.querylist/languageModels/typesystem.mps
`QueryListNodeExpression` provides access to the input node of the query, but due to its ambiguous alias (`node`) conflicts with the `ConceptFunctionParameter_node` parameter of the query function, which makes it easy to pick up the wrong expression without directly noticing this. Also the code using both expressions at the same time becomes confusing.
Furthermore, `QueryListNodeExpression` and `QueryListIndexExpression` are currently allowed to be used outside of the querylist inline editor component, i.e. when there is no loop through the query list yet and no need for accessing index and querylist input node. Also, using the expressions in the nested querylist resulted in a wrong node and index to be returned: if used in the nested querylist query, the values were incorrectly returned …
=> querylist: inline editor expressions improvements

CHANGELOG.md, code/celllayout/languages/de.itemis.mps.celllayout/models/styles/editor.mps, code/celllayout/solutions/de.slisson.mps.editor.celllayout.runtime/models/de/itemis/mps/editor/celllayout/runtime.mps, code/diagram/languages/de.itemis.mps.editor.diagram.demoentities/languageModels/editor.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
There is now also a new style attribute `-custom-border-painting` to circumvent the border painter of the celllayout language. To draw the border manually, call `Borderpainter#paintBorders` with isCustomPainting set to true.
This PR should also fix https://github.com/JetBrains/MPS-extensions/issues/81 but I could only reproduce half of the issue.
=> diagrams: make borders work in diagram boxes

CHANGELOG.md, code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/com.mbeddr.mpsutil.intentions.runtime.msd, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime/plugin.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps, code/solutions/com.mbeddr.mpsutil.intentions.tests/com.mbeddr.mpsutil.intentions.tests.msd, code/solutions/com.mbeddr.mpsutil.intentions.tests/models/com.mbeddr.mpsutil.intentions.tests.tests@tests.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Fixes #1233 by registring and overriding a new `alt ENTER` action. 
The bulb is (as before) not visible.
=> mpsuitl.intentions.runtime: override intentions action

code/hacks/solutions/de.slisson.mps.hacks.editor/models/de/slisson/mps/hacks/editor.mps, code/model-api/org.modelix.model.mpsadapters/models/org.modelix.model.mpsadapters.mps.mps
Not all SModule instances are AbstractModule.
And to remove some legacy API methods, we'd need their overrides not to demand their presence.
=> avoid CCE when not AbstractModule

CHANGELOG.md, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps, code/tables/languages/de.slisson.mps.tables.demolang/languageModels/editor.mps, code/tables/languages/de.slisson.mps.tables/generator/template/main@generator.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/gridmodel.mps
If there is no style, the style from the grid element 0x0 will be used. The application order is at the moment still sometimes incorrect. The most specific style is not used.
- fixes https://github.com/JetBrains/MPS-extensions/issues/553
=> slisson.mps.tables: try to apply more styles

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/celllayout/languages/de.itemis.mps.celllayout/models/styles/behavior.mps, code/celllayout/languages/de.itemis.mps.celllayout/models/styles/editor.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout.sandboxlang/de.itemis.mps.editor.celllayout.sandboxlang.mpl, code/celllayout/languages/de.itemis.mps.editor.celllayout.sandboxlang/models/editor.mps, code/celllayout/languages/de.itemis.mps.editor.celllayout.sandboxlang/models/structure.mps, code/celllayout/solutions/de.itemis.mps.editor.celllayout.sandbox/models/de/itemis/mps/editor/celllayout/sandbox.mps
This is an old branch of mine with a stylesheet [IntelliJStyleSheet](http://127.0.0.1:63320/node?ref=r%3A0b928dd6-dd7e-45a8-b309-a2e315b7877a%28de.itemis.mps.editor.celllayout.styles.editor%29%2F3571264999551554431) to emulate the style of the IntelliJ UI in the MPS editor. Examples for UI (Swing) components can be found in de.itemis.mps.editor.celllayout.sandbox.
=> Stylesheet + IntelliJ Ui experiments

build.gradle
Moved sbom.json into a subfolder of the published zip to avoid conflicts with other language libraries on extraction
=> Update sbom.json publication

build.gradle
This reverts commit 6fe5d9c972810df70baa7d0bb898519246292718. Cascading merges shouldn't touch MPS versions.
=> Revert "build: use MPS 2025.1-RC1"

code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/tables/languages/de.slisson.mps.tables/runtime/de.slisson.mps.tables.runtime.msd, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/gridmodel.mps, code/tables/solutions/test.de.slisson.mps.tables.runtime/models/test.de.slisson.mps.tables.runtime.gridmodel@tests.mps, code/tables/solutions/test.de.slisson.mps.tables.runtime/test.de.slisson.mps.tables.runtime.msd
This eliminates indirect dependency of tables.runtime on testing infrastructure.
=> tables: extract gridmodel tests to a separate solution

CHANGELOG.md, code/richtext/languages/richtext/languageModels/behavior.mps, code/richtext/solutions/test.de.slisson.mps.richtext/models/test.de.slisson.mps.richtext@tests.mps, code/richtext/solutions/test.de.slisson.mps.richtext/test.de.slisson.mps.richtext.msd, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Fixed utility class for creating instances of `Text` to avoid space ` ` before the actual string content. This might be helpful when requiring exact `Text` content, for example in nodes compare scenarios.
_Note_: fixed method  `RichTextUtil.createTextFromSingleString()` is only available as utility for the external usage, but not used in the richtext language itself. Therefore the change has no impact on the language behavior.
=> richtext: fixed RichTextUtil for Text creation

CHANGELOG.md, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/compare/languages/com.mbeddr.mpsutil.compare/generator/template/main@generator.mps, code/compare/languages/com.mbeddr.mpsutil.compare/languageModels/behavior.mps, code/compare/solutions/com.mbeddr.mpsutil.comparator/models/.model, code/compare/solutions/com.mbeddr.mpsutil.comparator/models/RepositoryHelper.mpsr, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/com.mbeddr.mpsutil.intentions.runtime.msd, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions.runtime/models/com/mbeddr/mpsutil/intentions/runtime/plugin.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/com.mbeddr.mpsutil.intentions.mpl, code/intentionsmenu/com.mbeddr.mpsutil.intentions/generator/template/main@generator.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/behavior.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/com.mbeddr.mpsutil.intentions.listeners.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/editor.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/intentions.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/structure.mps, code/intentionsmenu/com.mbeddr.mpsutil.intentions/languageModels/typesystem.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/com.mbeddr.mpsutil.intentions.sandboxlang.mpl, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.editor.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.intentions.mps, code/languages/com.mbeddr.mpsutil.intentions.sandboxlang/models/com.mbeddr.mpsutil.intentions.sandboxlang.structure.mps, code/solutions/com.mbeddr.mpsutil.intentions.sandbox/models/com.mbeddr.mpsutil.intentions.sandbox.sandbox.mps, code/solutions/com.mbeddr.mpsutil.intentions.tests/com.mbeddr.mpsutil.intentions.tests.msd, code/solutions/com.mbeddr.mpsutil.intentions.tests/models/com.mbeddr.mpsutil.intentions.tests.plugin.mps, code/solutions/com.mbeddr.mpsutil.intentions.tests/models/com.mbeddr.mpsutil.intentions.tests.tests@tests.mps, code/solutions/de.itemis.model.merge.test/models/de.itemis.model.merge.test.gen@tests.mps, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
Group annotations can now be also added to action declarations and are active when the actions are added to the *ActionsAsIntentions* group.
Known issues:
- The cache is not always invalidated. You have to restart MPS or Reload All Classes for the change to take effect.
- The is applicable block of actions is not evaluated. In the original implementation in MPS this also doesn't work.
=> mpsutil.intentions: Add support for grouping intention actions

.github/renovate.json5
Prevent from upgrading to -android, e.g. #1291.
=> renovate: allow only -jre versions of Guava

code/compare/languages/de.itemis.mps.compare.pattern/models/de.itemis.mps.compare.pattern.structure.mps, code/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells.sandboxlang/models/com/mbeddr/mpsutil/grammarcells/sandboxlang/structure.mps, code/grammarcells/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps, code/plaintextgen/languages/com.dslfoundry.plaintextgen/models/com/dslfoundry/plaintextgen/structure.mps, code/structurecheck/languages/de.itemis.mps.structurecheck/languageModels/structure.mps, code/tables/languages/de.slisson.mps.tables/languageModels/structure.mps, code/treenotation/com.mbeddr.mpsutil.treenotation/generator/template/main@generator.mps, code/widgets/languages/de.itemis.mps.editor.dropdown.demolang/languageModels/structure.mps, code/widgets/languages/de.itemis.mps.editor.enumeration.demolang/models/structure.mps
Instances of EnumerationDataTypeDeclaration_Old were necessary for enum migration back in 2019, it is safe to assume all usages have been migrated now.
=> Drop migration info for old EnumDataTypeDeclaration

CHANGELOG.md, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps, code/tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/plugin.mps, code/tables/solutions/test.de.slisson.mps.tables/models/test/de/slisson/mps/tables@tests.mps
Fixes #1461
In addition I added some editor tests for [TableAction_DeleteRow](http://127.0.0.1:63320/node?ref=r%3A53747654-8f0d-48ae-96f3-1e68e62f0a2f%28test.de.slisson.mps.tables%40tests%29%2F53021589582773546), [TableAction_InsertRowBefore](http://127.0.0.1:63320/node?ref=r%3A53747654-8f0d-48ae-96f3-1e68e62f0a2f%28test.de.slisson.mps.tables%40tests%29%2F53021589582902430), [TableAction_InsertRowAfter](http://127.0.0.1:63320/node?ref=r%3A53747654-8f0d-48ae-96f3-1e68e62f0a2f%28test.de.slisson.mps.tables%40tests%29%2F53021589582892364)
=> DeleteRowAction: made use of triggeredFromMPSAction flag

code/modellisteners/com.mbeddr.mpsutil.modellisteners.runtime/com.mbeddr.mpsutil.modellisteners.runtime.msd, code/modellisteners/com.mbeddr.mpsutil.modellisteners.runtime/models/com/mbeddr/mpsutil/modellisteners/runtime.mps, code/modellisteners/com.mbeddr.mpsutil.modellisteners.runtime/models/com/mbeddr/mpsutil/modellisteners/runtime/plugin.mps
This contains the part of PR #1439 that was focused on model listeners, a few clean ups to remove deprecated methods, and a refactoring to stop using `MPSModuleRepository.getInstance()`. No changes should be user-visible.
=> Model listeners per project

code/langvis/solutions/com.dslfoundry.langvis.plugin/models/com.dslfoundry.langvis.plugin.plugin.mps
- Factored `redrawPng()` out of rebuild
- Listener: pulled rebuild step out of invokeLater (requires read action)
This makes the rebuild immediate and controllable from an action (with read permissions).
Fixes #1550
=> Fix exception when visualizing language structure

code/shadowmodels/solutions/de.q60.mps.polymorphicfunctions.runtime/models/de.q60.mps.polymorphicfunctions.runtime.mps, code/shadowmodels/solutions/de.q60.mps.polymorphicfunctions.runtime/models/plugin.mps, code/shadowmodels/solutions/de.q60.mps.polymorphicfunctions.sandbox/models/functions@tests.mps
* Replace ReloadableModule w/ ModuleRuntime in DescriptorCache.
* ImplementationsFromFunctionModule: use ModuleRuntime to access generated classes.
Based on a contribution by Artem Tikhomirov (#1439).
=> polymorph func: use ModuleRuntime instead of deprecated ReloadableModule

code/.mps/.gitignore, code/.mps/modules.xml, code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/compare/solutions/de.itemis.mps.comparator.diff.tests/models/de.itemis.mps.comparator.diff.tests.diffs@tests.mps, code/hasher/solutions/nl.f1re.mpsutil.hasher.tests/models/nl.f1re.mpsutil.hasher.tests@tests.mps, code/hasher/solutions/nl.f1re.mpsutil.hasher.tests/nl.f1re.mpsutil.hasher.tests.msd, code/hasher/solutions/nl.f1re.mpsutil.hasher/models/nl.f1re.mpsutil.hasher.mps, code/hasher/solutions/nl.f1re.mpsutil.hasher/nl.f1re.mpsutil.hasher.msd, code/solutions/de.itemis.mps.extensions.changelog/models/de.itemis.mps.extensions.changelog.mps
implements #1531 
I put it into the `compare` plugin, as comparing and hashing nodes are quite similar (cf. Java `Object.equals()` and `Object.hashCode()`). This introduces a new dependency to `de.q60.mps.collections.libs`.
I used namespace `nl.f1re.mpsutil.hasher`.
Both of this can be adjusted.
=> added efficient NodeHasher

code/build/solutions/de.itemis.mps.extensions.build/models/de.itemis.mps.extensions.build.mps, code/diagram/solutions/de.itemis.mps.editor.diagram.runtime/de.itemis.mps.editor.diagram.runtime.msd
Do not add it to stubs because it appears to be runtime-only.
This fixes broken diagram libraries after ELK upgrade to 0.11.
=> diagram.runtime: add new xbase.lib dependency to libraries
